# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PROJECT_NAME: "notify_scrapy"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V # Print out python version for debugging
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install git+https://github.com/scrapy/scrapyd-client

run:
 stage: deploy
 tags:
    - deploy
 script:
    - scrapyd-client schedule -p $PROJECT_NAME \* # Run all spiders
 only:
    - master
    - schedules

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - scrapyd-deploy -p $PROJECT_NAME
  only:
    - master
  except:
    - schedules
