# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class AgricultureCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'agriculture_college_page0'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['首页', '最新通知']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/7522/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/7522/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w29"]/ul[@class="wp_article_list"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="Article_PublishDate"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class AgricultureCollegePage1Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page1'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['首页', '公告公示']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28889/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28889/list%d.htm'


class AgricultureCollegePage2Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page2'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党政综合', '规章制度']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28956/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28956/list%d.htm'


class AgricultureCollegePage3Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page3'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党政综合', '党委文件']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28957/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28957/list%d.htm'


class AgricultureCollegePage4Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page4'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党政综合', '学院年报']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28961/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28961/list%d.htm'


class AgricultureCollegePage5Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page5'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党政综合', '安全稳定', '相关通知']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29085/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29085/list%d.htm'


class AgricultureCollegePage6Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page6'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党政综合', '安全稳定', '实验室安全']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29086/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29086/list%d.htm'


class AgricultureCollegePage7Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page7'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党政综合', '安全稳定', '设备管理']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29087/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29087/list%d.htm'


class AgricultureCollegePage8Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page8'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党政综合', '安全稳定', '电子门锁']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29088/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29088/list%d.htm'


class AgricultureCollegePage9Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page9'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党政综合', '表格下载']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28963/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28963/list%d.htm'


class AgricultureCollegePage10Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page10'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['组织人事', '最新通知']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28964/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28964/list%d.htm'


class AgricultureCollegePage11Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page11'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['本科生教育', '通知公告']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28971/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28971/list%d.htm'


class AgricultureCollegePage12Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page12'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['本科生教育', '新闻动态']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/xwdt_47071/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/xwdt_47071/list%d.htm'


class AgricultureCollegePage13Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page13'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['本科生教育', '教学培养']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28972/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28972/list%d.htm'


class AgricultureCollegePage14Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page14'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['本科生教育', '对外交流']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28974/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28974/list%d.htm'


class AgricultureCollegePage15Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page15'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['本科生教育', '文件汇编']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28977/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28977/list%d.htm'


class AgricultureCollegePage16Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page16'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['本科生教育', '表格下载']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28978/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28978/list%d.htm'


class AgricultureCollegePage17Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page17'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['研究生教育', '最新通知']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28979/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28979/list%d.htm'


class AgricultureCollegePage18Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page18'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['研究生教育', '招生信息']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28981/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28981/list%d.htm'


class AgricultureCollegePage19Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page19'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '最新通知']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28989/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28989/list%d.htm'


class AgricultureCollegePage20Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page20'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '科研政策']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28991/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28991/list%d.htm'


class AgricultureCollegePage21Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page21'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '科研项目']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28992/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28992/list%d.htm'


class AgricultureCollegePage22Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page22'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '科研成果', '科研论文']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29022/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29022/list%d.htm'


class AgricultureCollegePage23Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page23'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '科研成果', '科研奖励']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29023/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29023/list%d.htm'


class AgricultureCollegePage24Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page24'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '科研成果', '授权专利']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29024/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29024/list%d.htm'


class AgricultureCollegePage25Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page25'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '科研成果', '审定品种']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29025/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29025/list%d.htm'


class AgricultureCollegePage26Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page26'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '科研成果', '其他成果']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/qtcg/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/qtcg/list%d.htm'


class AgricultureCollegePage27Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page27'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '办事流程']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28997/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28997/list%d.htm'


class AgricultureCollegePage28Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page28'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['科研与地方合作', '下载专区']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28998/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28998/list%d.htm'


class AgricultureCollegePage29Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page29'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['国际合作与交流', '通知公告']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/28999/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/28999/list%d.htm'


class AgricultureCollegePage30Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page30'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['国际合作与交流', '师生交流']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29000/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29000/list%d.htm'


class AgricultureCollegePage31Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page31'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['国际合作与交流', '办事指南']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29001/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29001/list%d.htm'


class AgricultureCollegePage32Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page32'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['学院工会', '最新通知']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29003/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29003/list%d.htm'


class AgricultureCollegePage33Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page33'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['学院工会', '服务信息']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29006/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29006/list%d.htm'


class AgricultureCollegePage34Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page34'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党建工作', '重要通知']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29010/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29010/list%d.htm'


class AgricultureCollegePage35Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page35'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党建工作', '公示公告']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/gsgg/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/gsgg/list%d.htm'


class AgricultureCollegePage36Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page36'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党建工作', '文件资料', '上级文件']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/29012/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/29012/list%d.htm'


class AgricultureCollegePage37Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page37'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党建工作', '文件资料', '学院发文']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/xyfw/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/xyfw/list%d.htm'


class AgricultureCollegePage38Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page38'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党建工作', '党务工作']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/dwgz/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/dwgz/list%d.htm'


class AgricultureCollegePage39Spider(AgricultureCollegePage0Spider):
    name = 'agriculture_college_page39'
    source = '2'
    publisher = '农业与生物技术学院'
    column = ['党建工作', '表格下载']
    start_urls = ['http://www.cab.zju.edu.cn/bgw/bgxz_43310/list.htm']
    page_url = 'http://www.cab.zju.edu.cn/bgw/bgxz_43310/list%d.htm'
