# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class BeisCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'beis_college_page0'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['院党政办', '工作通报']
    start_urls = ['http://office.cbeis.zju.edu.cn/23347/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23347/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w35"]//li'
    title_xpath = './/@title'
    url_xpath = './a/@href'
    publish_time_xpath = './/span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class BeisCollegePage1Spider(BeisCollegePage0Spider):
    name = 'beis_college_page1'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['院党政办', '学院文件']
    start_urls = ['http://office.cbeis.zju.edu.cn/23348/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23348/list%d.htm'


class BeisCollegePage2Spider(BeisCollegePage0Spider):
    name = 'beis_college_page2'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['院党政办', '会议纪要']
    start_urls = ['http://office.cbeis.zju.edu.cn/23349/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23349/list%d.htm'


class BeisCollegePage3Spider(BeisCollegePage0Spider):
    name = 'beis_college_page3'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['院党政办', '规章制度']
    start_urls = ['http://office.cbeis.zju.edu.cn/23350/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23350/list%d.htm'


class BeisCollegePage4Spider(BeisCollegePage0Spider):
    name = 'beis_college_page4'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['院党政办', '工作职责']
    start_urls = ['http://office.cbeis.zju.edu.cn/23353/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23353/list%d.htm'


class BeisCollegePage5Spider(BeisCollegePage0Spider):
    name = 'beis_college_page5'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['队伍建设', '通知公告']
    start_urls = ['http://office.cbeis.zju.edu.cn/23354/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23354/list%d.htm'


class BeisCollegePage6Spider(BeisCollegePage0Spider):
    name = 'beis_college_page6'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['队伍建设', '师资队伍']
    start_urls = ['http://office.cbeis.zju.edu.cn/23355/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23355/list%d.htm'


class BeisCollegePage7Spider(BeisCollegePage0Spider):
    name = 'beis_college_page7'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['队伍建设', '人才引进']
    start_urls = ['http://office.cbeis.zju.edu.cn/23356/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23356/list%d.htm'


class BeisCollegePage8Spider(BeisCollegePage0Spider):
    name = 'beis_college_page8'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['队伍建设', '管理制度']
    start_urls = ['http://office.cbeis.zju.edu.cn/23357/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23357/list%d.htm'


class BeisCollegePage9Spider(BeisCollegePage0Spider):
    name = 'beis_college_page9'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['科研管理', '通知公告']
    start_urls = ['http://office.cbeis.zju.edu.cn/23358/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23358/list%d.htm'


class BeisCollegePage10Spider(BeisCollegePage0Spider):
    name = 'beis_college_page10'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['科研管理', '科研成果']
    start_urls = ['http://office.cbeis.zju.edu.cn/23360/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23360/list%d.htm'


class BeisCollegePage11Spider(BeisCollegePage0Spider):
    name = 'beis_college_page11'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['科研管理', '科研政策']
    start_urls = ['http://office.cbeis.zju.edu.cn/23361/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23361/list%d.htm'


class BeisCollegePage12Spider(BeisCollegePage0Spider):
    name = 'beis_college_page12'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['科研管理', '科研动态']
    start_urls = ['http://office.cbeis.zju.edu.cn/23362/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23362/list%d.htm'


class BeisCollegePage13Spider(BeisCollegePage0Spider):
    name = 'beis_college_page13'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['本科生教学', '通知公告']
    start_urls = ['http://office.cbeis.zju.edu.cn/23363/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23363/list%d.htm'


class BeisCollegePage14Spider(BeisCollegePage0Spider):
    name = 'beis_college_page14'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['本科生教学', '会议纪要']
    start_urls = ['http://office.cbeis.zju.edu.cn/23364/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23364/list%d.htm'


class BeisCollegePage15Spider(BeisCollegePage0Spider):
    name = 'beis_college_page15'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['本科生教学', '文件汇编']
    start_urls = ['http://office.cbeis.zju.edu.cn/23365/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23365/list%d.htm'


class BeisCollegePage16Spider(BeisCollegePage0Spider):
    name = 'beis_college_page16'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['本科生教学', '表格下载']
    start_urls = ['http://office.cbeis.zju.edu.cn/23366/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23366/list%d.htm'


class BeisCollegePage17Spider(BeisCollegePage0Spider):
    name = 'beis_college_page17'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['本科生教学', '专业确认']
    start_urls = ['http://office.cbeis.zju.edu.cn/23367/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23367/list%d.htm'


class BeisCollegePage18Spider(BeisCollegePage0Spider):
    name = 'beis_college_page18'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['本科生教学', '服务指南']
    start_urls = ['http://office.cbeis.zju.edu.cn/23368/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23368/list%d.htm'


class BeisCollegePage19Spider(BeisCollegePage0Spider):
    name = 'beis_college_page19'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['本科生教学', '本科新闻']
    start_urls = ['http://office.cbeis.zju.edu.cn/23369/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23369/list%d.htm'


class BeisCollegePage20Spider(BeisCollegePage0Spider):
    name = 'beis_college_page20'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['研究生教学', '招生信息']
    start_urls = ['http://office.cbeis.zju.edu.cn/23370/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23370/list%d.htm'


class BeisCollegePage21Spider(BeisCollegePage0Spider):
    name = 'beis_college_page21'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['研究生教学', '通知公告']
    start_urls = ['http://office.cbeis.zju.edu.cn/23371/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23371/list%d.htm'


class BeisCollegePage22Spider(BeisCollegePage0Spider):
    name = 'beis_college_page22'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['研究生教学', '文件汇编']
    start_urls = ['http://office.cbeis.zju.edu.cn/23373/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23373/list%d.htm'


class BeisCollegePage23Spider(BeisCollegePage0Spider):
    name = 'beis_college_page23'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['研究生教学', '新闻列表']
    start_urls = ['http://office.cbeis.zju.edu.cn/23374/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23374/list%d.htm'


class BeisCollegePage24Spider(BeisCollegePage0Spider):
    name = 'beis_college_page24'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['思政工作', '通知公告']
    start_urls = ['http://office.cbeis.zju.edu.cn/23375/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23375/list%d.htm'


class BeisCollegePage25Spider(BeisCollegePage0Spider):
    name = 'beis_college_page25'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['思政工作', '学生党建']
    start_urls = ['http://office.cbeis.zju.edu.cn/23377/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23377/list%d.htm'


class BeisCollegePage26Spider(BeisCollegePage0Spider):
    name = 'beis_college_page26'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['思政工作', '学院团委']
    start_urls = ['http://office.cbeis.zju.edu.cn/23378/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23378/list%d.htm'


class BeisCollegePage27Spider(BeisCollegePage0Spider):
    name = 'beis_college_page27'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['思政工作', '思政新闻']
    start_urls = ['http://office.cbeis.zju.edu.cn/23379/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23379/list%d.htm'


class BeisCollegePage28Spider(BeisCollegePage0Spider):
    name = 'beis_college_page28'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['对外交流', '通知公告']
    start_urls = ['http://office.cbeis.zju.edu.cn/23380/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23380/list%d.htm'


class BeisCollegePage29Spider(BeisCollegePage0Spider):
    name = 'beis_college_page29'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['对外交流', '交流项目']
    start_urls = ['http://office.cbeis.zju.edu.cn/23381/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23381/list%d.htm'


class BeisCollegePage30Spider(BeisCollegePage0Spider):
    name = 'beis_college_page30'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['对外交流', '外事动态']
    start_urls = ['http://office.cbeis.zju.edu.cn/23383/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23383/list%d.htm'


class BeisCollegePage31Spider(BeisCollegePage0Spider):
    name = 'beis_college_page31'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['实验中心', '通知公告']
    start_urls = ['http://office.cbeis.zju.edu.cn/23384/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23384/list%d.htm'


class BeisCollegePage32Spider(BeisCollegePage0Spider):
    name = 'beis_college_page32'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['实验中心', '职责制度']
    start_urls = ['http://office.cbeis.zju.edu.cn/23385/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23385/list%d.htm'


class BeisCollegePage33Spider(BeisCollegePage0Spider):
    name = 'beis_college_page33'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['实验中心', '实践教学']
    start_urls = ['http://office.cbeis.zju.edu.cn/23386/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23386/list%d.htm'


class BeisCollegePage34Spider(BeisCollegePage0Spider):
    name = 'beis_college_page34'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['实验中心', '设备管理']
    start_urls = ['http://office.cbeis.zju.edu.cn/23387/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23387/list%d.htm'


class BeisCollegePage35Spider(BeisCollegePage0Spider):
    name = 'beis_college_page35'
    source = '5'
    publisher = '生物医学工程与仪器科学学院'
    column = ['教工之家', '最新通知']
    start_urls = ['http://office.cbeis.zju.edu.cn/23389/list.htm']
    page_url = 'http://office.cbeis.zju.edu.cn/23389/list%d.htm'
