# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class ElectricalEngineeringCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'electrical_engineering_college_page0'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '信息公告']
    start_urls = ['http://ee.office.zju.edu.cn/33869/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33869/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="news_list list2"]/li'
    title_xpath = './/a/text()'
    url_xpath = './/a/@href'
    publish_time_xpath = './span[@class="news_meta"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class ElectricalEngineeringCollegePage1Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page1'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '办事指南']
    start_urls = ['http://ee.office.zju.edu.cn/33870/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33870/list%d.htm'


class ElectricalEngineeringCollegePage2Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page2'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '主修专业确认']
    start_urls = ['http://ee.office.zju.edu.cn/33871/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33871/list%d.htm'


class ElectricalEngineeringCollegePage3Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page3'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '对外交流']
    start_urls = ['http://ee.office.zju.edu.cn/33872/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33872/list%d.htm'


class ElectricalEngineeringCollegePage4Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page4'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '爱迪生实验班']
    start_urls = ['http://ee.office.zju.edu.cn/33873/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33873/list%d.htm'


class ElectricalEngineeringCollegePage5Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page5'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '科研训练&竞赛']
    start_urls = ['http://ee.office.zju.edu.cn/33874/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33874/list%d.htm'


class ElectricalEngineeringCollegePage6Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page6'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '实习与实践']
    start_urls = ['http://ee.office.zju.edu.cn/33875/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33875/list%d.htm'


class ElectricalEngineeringCollegePage7Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page7'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '卓越工程师计划']
    start_urls = ['http://ee.office.zju.edu.cn/33876/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33876/list%d.htm'


class ElectricalEngineeringCollegePage8Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page8'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '毕业设计']
    start_urls = ['http://ee.office.zju.edu.cn/33877/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33877/list%d.htm'


class ElectricalEngineeringCollegePage9Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page9'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '课程与实验室建设']
    start_urls = ['http://ee.office.zju.edu.cn/33878/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33878/list%d.htm'


class ElectricalEngineeringCollegePage10Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page10'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '免试研究生推荐']
    start_urls = ['http://ee.office.zju.edu.cn/33879/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33879/list%d.htm'


class ElectricalEngineeringCollegePage11Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page11'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '教学事务']
    start_urls = ['http://ee.office.zju.edu.cn/33880/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33880/list%d.htm'


class ElectricalEngineeringCollegePage12Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page12'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '资料下载']
    start_urls = ['http://ee.office.zju.edu.cn/33881/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33881/list%d.htm'


class ElectricalEngineeringCollegePage13Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page13'
    source = '15'
    publisher = '电气工程学院'
    column = ['本科生教育', '文件汇编']
    start_urls = ['http://ee.office.zju.edu.cn/wjhb/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/wjhb/list%d.htm'


class ElectricalEngineeringCollegePage14Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page14'
    source = '15'
    publisher = '电气工程学院'
    column = ['国际交流', '国际交流项目']
    start_urls = ['http://ee.office.zju.edu.cn/33903/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33903/list%d.htm'


class ElectricalEngineeringCollegePage15Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page15'
    source = '15'
    publisher = '电气工程学院'
    column = ['学生工作', '信息公告']
    start_urls = ['http://ee.office.zju.edu.cn/33906/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33906/list%d.htm'


class ElectricalEngineeringCollegePage16Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page16'
    source = '15'
    publisher = '电气工程学院'
    column = ['学生工作', '学生活动']
    start_urls = ['http://ee.office.zju.edu.cn/33907/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33907/list%d.htm'


class ElectricalEngineeringCollegePage17Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page17'
    source = '15'
    publisher = '电气工程学院'
    column = ['学生工作', '党团建设']
    start_urls = ['http://ee.office.zju.edu.cn/33908/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33908/list%d.htm'


class ElectricalEngineeringCollegePage18Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page18'
    source = '15'
    publisher = '电气工程学院'
    column = ['学生工作', '荣誉成果']
    start_urls = ['http://ee.office.zju.edu.cn/33909/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33909/list%d.htm'


class ElectricalEngineeringCollegePage19Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page19'
    source = '15'
    publisher = '电气工程学院'
    column = ['就业服务', '重要通知']
    start_urls = ['http://ee.office.zju.edu.cn/33912/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33912/list%d.htm'


class ElectricalEngineeringCollegePage20Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page20'
    source = '15'
    publisher = '电气工程学院'
    column = ['就业服务', '招聘资讯', '招聘信息']
    start_urls = ['http://ee.office.zju.edu.cn/33914/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33914/list%d.htm'


class ElectricalEngineeringCollegePage21Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page21'
    source = '15'
    publisher = '电气工程学院'
    column = ['就业服务', '招聘资讯', '招聘实习']
    start_urls = ['http://ee.office.zju.edu.cn/33916/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33916/list%d.htm'


class ElectricalEngineeringCollegePage22Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page22'
    source = '15'
    publisher = '电气工程学院'
    column = ['就业服务', '招聘资讯', '考研调剂']
    start_urls = ['http://ee.office.zju.edu.cn/33917/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/33917/list%d.htm'


class ElectricalEngineeringCollegePage23Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page23'
    source = '15'
    publisher = '电气工程学院'
    column = ['就业服务', '生涯规划', '就业指导与培训']
    start_urls = ['http://ee.office.zju.edu.cn/jzpx/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/jzpx/list%d.htm'


class ElectricalEngineeringCollegePage24Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page24'
    source = '15'
    publisher = '电气工程学院'
    column = ['就业服务', '生涯规划', '职规大赛']
    start_urls = ['http://ee.office.zju.edu.cn/51850/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/51850/list%d.htm'


class ElectricalEngineeringCollegePage25Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page25'
    source = '15'
    publisher = '电气工程学院'
    column = ['就业服务', '生涯规划', '生涯资讯']
    start_urls = ['http://ee.office.zju.edu.cn/51851/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/51851/list%d.htm'


class ElectricalEngineeringCollegePage26Spider(ElectricalEngineeringCollegePage0Spider):
    name = 'electrical_engineering_college_page26'
    source = '15'
    publisher = '电气工程学院'
    column = ['就业服务', '生涯规划', '资讯预约']
    start_urls = ['http://ee.office.zju.edu.cn/zxyy/list.htm']
    page_url = 'http://ee.office.zju.edu.cn/zxyy/list%d.htm'
