# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class EnergyCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'energy_college_page0'
    source = '16'
    publisher = '能源工程学院'
    column = ['能源新闻', '能源要闻']
    start_urls = ['http://doe-oa.zju.edu.cn/nyyw/list1.htm']
    page_url = 'http://doe-oa.zju.edu.cn/nyyw/list1list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="cg-news-list"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class EnergyCollegePage1Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page1'
    source = '16'
    publisher = '能源工程学院'
    column = ['能源新闻', '学术进展']
    start_urls = ['http://doe-oa.zju.edu.cn/xsjz_30730/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/xsjz_30730/list%d.htm'


class EnergyCollegePage2Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page2'
    source = '16'
    publisher = '能源工程学院'
    column = ['能源新闻', '快讯', '学术活动']
    start_urls = ['http://doe-oa.zju.edu.cn/xshd/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/xshd/list%d.htm'


class EnergyCollegePage3Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page3'
    source = '16'
    publisher = '能源工程学院'
    column = ['能源新闻', '快讯', '支部风采']
    start_urls = ['http://doe-oa.zju.edu.cn/zbfc/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/zbfc/list%d.htm'


class EnergyCollegePage4Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page4'
    source = '16'
    publisher = '能源工程学院'
    column = ['能源新闻', '快讯', '工会活动']
    start_urls = ['http://doe-oa.zju.edu.cn/ghhd/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/ghhd/list%d.htm'


class EnergyCollegePage5Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page5'
    source = '16'
    publisher = '能源工程学院'
    column = ['能源新闻', '快讯', '学生活动']
    start_urls = ['http://doe-oa.zju.edu.cn/xshd_30740/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/xshd_30740/list%d.htm'


class EnergyCollegePage6Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page6'
    source = '16'
    publisher = '能源工程学院'
    column = ['能源新闻', '快讯', '学院综合']
    start_urls = ['http://doe-oa.zju.edu.cn/xyzh/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/xyzh/list%d.htm'


class EnergyCollegePage7Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page7'
    source = '16'
    publisher = '能源工程学院'
    column = ['本科生教育', '信息公告']
    start_urls = ['http://doe-oa.zju.edu.cn/24611/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24611/list%d.htm'


class EnergyCollegePage8Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page8'
    source = '16'
    publisher = '能源工程学院'
    column = ['本科生教育', '专业确认']
    start_urls = ['http://doe-oa.zju.edu.cn/24612/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24612/list%d.htm'


class EnergyCollegePage9Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page9'
    source = '16'
    publisher = '能源工程学院'
    column = ['科学研究', '信息公告']
    start_urls = ['http://doe-oa.zju.edu.cn/24628/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24628/list%d.htm'


class EnergyCollegePage10Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page10'
    source = '16'
    publisher = '能源工程学院'
    column = ['科学研究', '科研动态']
    start_urls = ['http://doe-oa.zju.edu.cn/24629/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24629/list%d.htm'


class EnergyCollegePage11Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page11'
    source = '16'
    publisher = '能源工程学院'
    column = ['科学研究', '科研成果']
    start_urls = ['http://doe-oa.zju.edu.cn/24630/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24630/list%d.htm'


class EnergyCollegePage12Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page12'
    source = '16'
    publisher = '能源工程学院'
    column = ['科学研究', '文件汇编', '学校文件']
    start_urls = ['http://doe-oa.zju.edu.cn/24817/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24817/list%d.htm'


class EnergyCollegePage13Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page13'
    source = '16'
    publisher = '能源工程学院'
    column = ['科学研究', '文件汇编', '学校以外文件']
    start_urls = ['http://doe-oa.zju.edu.cn/24818/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24818/list%d.htm'


class EnergyCollegePage14Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page14'
    source = '16'
    publisher = '能源工程学院'
    column = ['科学研究', '文件汇编', '科研经费相关文件']
    start_urls = ['http://doe-oa.zju.edu.cn/24819/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24819/list%d.htm'


class EnergyCollegePage15Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page15'
    source = '16'
    publisher = '能源工程学院'
    column = ['学生工作', '团委']
    start_urls = ['http://doe-oa.zju.edu.cn/24633/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24633/list%d.htm'


class EnergyCollegePage16Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page16'
    source = '16'
    publisher = '能源工程学院'
    column = ['学生工作', '学生党建']
    start_urls = ['http://doe-oa.zju.edu.cn/24634/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24634/list%d.htm'


class EnergyCollegePage17Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page17'
    source = '16'
    publisher = '能源工程学院'
    column = ['学生工作', '学工']
    start_urls = ['http://doe-oa.zju.edu.cn/24635/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24635/list%d.htm'


class EnergyCollegePage18Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page18'
    source = '16'
    publisher = '能源工程学院'
    column = ['学生工作', '研工']
    start_urls = ['http://doe-oa.zju.edu.cn/24636/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24636/list%d.htm'


class EnergyCollegePage19Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page19'
    source = '16'
    publisher = '能源工程学院'
    column = ['学生工作', '学生会']
    start_urls = ['http://doe-oa.zju.edu.cn/24637/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24637/list%d.htm'


class EnergyCollegePage20Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page20'
    source = '16'
    publisher = '能源工程学院'
    column = ['就业指导', '重点引导']
    start_urls = ['http://doe-oa.zju.edu.cn/zdyd/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/zdyd/list%d.htm'


class EnergyCollegePage21Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page21'
    source = '16'
    publisher = '能源工程学院'
    column = ['就业指导', '通知公告']
    start_urls = ['http://doe-oa.zju.edu.cn/24821/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24821/list%d.htm'


class EnergyCollegePage22Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page22'
    source = '16'
    publisher = '能源工程学院'
    column = ['就业指导', '招聘信息', '招聘信息']
    start_urls = ['http://doe-oa.zju.edu.cn/24822/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/24822/list%d.htm'


class EnergyCollegePage23Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page23'
    source = '16'
    publisher = '能源工程学院'
    column = ['就业指导', '招聘信息', '党政机关']
    start_urls = ['http://doe-oa.zju.edu.cn/56885/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/56885/list%d.htm'


class EnergyCollegePage24Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page24'
    source = '16'
    publisher = '能源工程学院'
    column = ['就业指导', '招聘信息', '事业单位']
    start_urls = ['http://doe-oa.zju.edu.cn/56886/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/56886/list%d.htm'


class EnergyCollegePage25Spider(EnergyCollegePage0Spider):
    name = 'energy_college_page25'
    source = '16'
    publisher = '能源工程学院'
    column = ['就业指导', '招聘信息', '企业单位']
    start_urls = ['http://doe-oa.zju.edu.cn/56887/list.htm']
    page_url = 'http://doe-oa.zju.edu.cn/56887/list%d.htm'
