# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class GlobalEngagementPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'global_engagement_page0'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['合作交流', '学生项目']
    start_urls = ['http://www.ir.zju.edu.cn/131/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/131/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="cg-news-list news"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="art-date"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '学院行政'


class GlobalEngagementPage1Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page1'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['出国出境', '规章制度']
    start_urls = ['http://www.ir.zju.edu.cn/140/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/140/list%d.htm'


class GlobalEngagementPage2Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page2'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['出国出境', '通知公告']
    start_urls = ['http://www.ir.zju.edu.cn/140a/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/140a/list%d.htm'


class GlobalEngagementPage3Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page3'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['出国出境', '信息公开']
    start_urls = ['http://www.ir.zju.edu.cn/145/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/145/list%d.htm'


class GlobalEngagementPage4Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page4'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['国际会议', '通知公告']
    start_urls = ['http://www.ir.zju.edu.cn/147/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/147/list%d.htm'


class GlobalEngagementPage5Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page5'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['国际会议', '最新动态']
    start_urls = ['http://www.ir.zju.edu.cn/146/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/146/list%d.htm'


class GlobalEngagementPage6Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page6'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['港澳台事务', '学生交流', '项目通知']
    start_urls = ['http://www.ir.zju.edu.cn/146/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/146/list%d.htm'


class GlobalEngagementPage7Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page7'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['港澳台事务', '交流动态']
    start_urls = ['http://www.ir.zju.edu.cn/13167/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/13167/list%d.htm'


class GlobalEngagementPage8Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page8'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['港澳台事务', '重要通知']
    start_urls = ['http://www.ir.zju.edu.cn/13168/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/13168/list%d.htm'


class GlobalEngagementPage9Spider(GlobalEngagementPage0Spider):
    name = 'global_engagement_page9'
    source = '18'
    publisher = '国际合作与交流处'
    column = ['党建园地', '公告公示']
    start_urls = ['http://www.ir.zju.edu.cn/163/list.htm']
    page_url = 'http://www.ir.zju.edu.cn/163/list%d.htm'
