# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class MedicineSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'medicine_school_page0'
    source = '32'
    publisher = '医学院'
    column = ['教育教学', '本科生教育', '日常通知']
    start_urls = ['http://www.cmm.zju.edu.cn/38704/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38704/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="yixue-news-ul"]/li'
    title_xpath = './/p[@class="yixue-news-first-p"]/text()'
    url_xpath = './/a/@href'
    publish_time_xpath = './p[@class="yixue-news-second-p"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class MedicineSchoolPage1Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page1'
    source = '32'
    publisher = '医学院'
    column = ['教育教学', '本科生教育', '重点提示']
    start_urls = ['http://www.cmm.zju.edu.cn/38712/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38712/list%d.htm'


class MedicineSchoolPage2Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page2'
    source = '32'
    publisher = '医学院'
    column = ['教育教学', '本科生教育', '考务管理']
    start_urls = ['http://www.cmm.zju.edu.cn/44371/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/44371/list%d.htm'


class MedicineSchoolPage3Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page3'
    source = '32'
    publisher = '医学院'
    column = ['教育教学', '本科生教育', '对外交流']
    start_urls = ['http://www.cmm.zju.edu.cn/44372/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/44372/list%d.htm'


class MedicineSchoolPage4Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page4'
    source = '32'
    publisher = '医学院'
    column = ['教育教学', '本科生教育', '文件制度']
    start_urls = ['http://www.cmm.zju.edu.cn/44373/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/44373/list%d.htm'


class MedicineSchoolPage5Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page5'
    source = '32'
    publisher = '医学院'
    column = ['合作交流', '国际交流']
    start_urls = ['http://www.cmm.zju.edu.cn/38775/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38775/list%d.htm'


class MedicineSchoolPage6Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page6'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '本科生', '新闻动态']
    start_urls = ['http://www.cmm.zju.edu.cn/38789/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38789/list%d.htm'


class MedicineSchoolPage7Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page7'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '本科生', '学生党建']
    start_urls = ['http://www.cmm.zju.edu.cn/44371/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/44371/list%d.htm'


class MedicineSchoolPage8Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page8'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '本科生', '评奖评优']
    start_urls = ['http://www.cmm.zju.edu.cn/38791/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38791/list%d.htm'


class MedicineSchoolPage9Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page9'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '本科生', '学生资助']
    start_urls = ['http://www.cmm.zju.edu.cn/38792/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38792/list%d.htm'


class MedicineSchoolPage10Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page10'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '本科生', '就业指导']
    start_urls = ['http://www.cmm.zju.edu.cn/38793/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38793/list%d.htm'


class MedicineSchoolPage11Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page11'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '本科生', '其他工作']
    start_urls = ['http://www.cmm.zju.edu.cn/38794/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38794/list%d.htm'


class MedicineSchoolPage12Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page12'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '本科生', '年级管理']
    start_urls = ['http://www.cmm.zju.edu.cn/38795/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38795/list%d.htm'


class MedicineSchoolPage13Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page13'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '团委', '重要通知']
    start_urls = ['http://www.cmm.zju.edu.cn/38806/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38806/list%d.htm'


class MedicineSchoolPage14Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page14'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '团委', '组织宣传']
    start_urls = ['http://www.cmm.zju.edu.cn/44371/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/44371/list%d.htm'


class MedicineSchoolPage15Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page15'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '团委', '志愿服务']
    start_urls = ['http://www.cmm.zju.edu.cn/38804/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38804/list%d.htm'


class MedicineSchoolPage16Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page16'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '团委', '社会实践']
    start_urls = ['http://www.cmm.zju.edu.cn/38803/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38803/list%d.htm'


class MedicineSchoolPage17Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page17'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '团委', '素质拓展']
    start_urls = ['http://www.cmm.zju.edu.cn/38802/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38802/list%d.htm'


class MedicineSchoolPage18Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page18'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '团委', '科技文化']
    start_urls = ['http://www.cmm.zju.edu.cn/38801/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38801/list%d.htm'


class MedicineSchoolPage19Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page19'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '团委', '学生社团']
    start_urls = ['http://www.cmm.zju.edu.cn/38800/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38800/list%d.htm'


class MedicineSchoolPage20Spider(MedicineSchoolPage0Spider):
    name = 'medicine_school_page20'
    source = '32'
    publisher = '医学院'
    column = ['学生工作', '团委', '学生会']
    start_urls = ['http://www.cmm.zju.edu.cn/38799/list.htm']
    page_url = 'http://www.cmm.zju.edu.cn/38799/list%d.htm'
