# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class MediaCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'media_college_page0'
    source = '31'
    publisher = '传媒与国际文化学院'
    column = ['学院动态', '重点关注']
    start_urls = ['http://www.cmic.zju.edu.cn/35553/list.htm']
    page_url = 'http://www.cmic.zju.edu.cn/35553/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="cg-news-list"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class MediaCollegePage1Spider(MediaCollegePage0Spider):
    name = 'media_college_page1'
    source = '31'
    publisher = '传媒与国际文化学院'
    column = ['学院动态', '信息速递']
    start_urls = ['http://www.cmic.zju.edu.cn/35554/list.htm']
    page_url = 'http://www.cmic.zju.edu.cn/35554/list%d.htm'


class MediaCollegePage2Spider(MediaCollegePage0Spider):
    name = 'media_college_page2'
    source = '31'
    publisher = '传媒与国际文化学院'
    column = ['学院动态', '活动预告']
    start_urls = ['http://www.cmic.zju.edu.cn/35555/list.htm']
    page_url = 'http://www.cmic.zju.edu.cn/35555/list%d.htm'


class MediaCollegePage3Spider(MediaCollegePage0Spider):
    name = 'media_college_page3'
    source = '31'
    publisher = '传媒与国际文化学院'
    column = ['合作交流', '国际合作']
    start_urls = ['http://www.cmic.zju.edu.cn/35577/list.htm']
    page_url = 'http://www.cmic.zju.edu.cn/35577/list%d.htm'


class MediaCollegePage4Spider(MediaCollegePage0Spider):
    name = 'media_college_page4'
    source = '31'
    publisher = '传媒与国际文化学院'
    column = ['传媒风采', '学子风采']
    start_urls = ['http://www.cmic.zju.edu.cn/xzfc/list.htm']
    page_url = 'http://www.cmic.zju.edu.cn/xzfc/list%d.htm'
