# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class PharmaceuticalCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'pharmaceutical_college_page0'
    source = '34'
    publisher = '药学院'
    column = ['学工团委', '重要通知']
    start_urls = ['http://office.cps.zju.edu.cn/zytz_26474/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/zytz_26474/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="news-ul"]/li'
    title_xpath = './/a[2]/text()'
    url_xpath = './/a[1]/@href'
    publish_time_xpath = './span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class PharmaceuticalCollegePage1Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page1'
    source = '34'
    publisher = '药学院'
    column = ['学工团委', '评奖评优']
    start_urls = ['http://office.cps.zju.edu.cn/pjpy/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/pjpy/list%d.htm'


class PharmaceuticalCollegePage2Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page2'
    source = '34'
    publisher = '药学院'
    column = ['学工团委', '就业工作']
    start_urls = ['http://office.cps.zju.edu.cn/jygz/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/jygz/list%d.htm'


class PharmaceuticalCollegePage3Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page3'
    source = '34'
    publisher = '药学院'
    column = ['学工团委', '信息动态']
    start_urls = ['http://office.cps.zju.edu.cn/xxdt_26475/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/xxdt_26475/list%d.htm'


class PharmaceuticalCollegePage4Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page4'
    source = '34'
    publisher = '药学院'
    column = ['学工团委', '党团建设']
    start_urls = ['http://office.cps.zju.edu.cn/dtjs/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/dtjs/list%d.htm'


class PharmaceuticalCollegePage5Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page5'
    source = '34'
    publisher = '药学院'
    column = ['学工团委', '勤工资助']
    start_urls = ['http://office.cps.zju.edu.cn/qgzz/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/qgzz/list%d.htm'


class PharmaceuticalCollegePage6Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page6'
    source = '34'
    publisher = '药学院'
    column = ['本科生教育', '教学教务']
    start_urls = ['http://office.cps.zju.edu.cn/jxjw/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/jxjw/list%d.htm'


class PharmaceuticalCollegePage7Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page7'
    source = '34'
    publisher = '药学院'
    column = ['本科生教育', '教学教改']
    start_urls = ['http://office.cps.zju.edu.cn/jxjg/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/jxjg/list%d.htm'


class PharmaceuticalCollegePage8Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page8'
    source = '34'
    publisher = '药学院'
    column = ['本科生教育', '专业确认']
    start_urls = ['http://office.cps.zju.edu.cn/zyqr/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/zyqr/list%d.htm'


class PharmaceuticalCollegePage9Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page9'
    source = '34'
    publisher = '药学院'
    column = ['本科生教育', '科研训练']
    start_urls = ['http://office.cps.zju.edu.cn/kyxl/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/kyxl/list%d.htm'


class PharmaceuticalCollegePage10Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page10'
    source = '34'
    publisher = '药学院'
    column = ['本科生教育', '毕业实习']
    start_urls = ['http://office.cps.zju.edu.cn/bysx/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/bysx/list%d.htm'


class PharmaceuticalCollegePage11Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page11'
    source = '34'
    publisher = '药学院'
    column = ['国际交流', '重要通知']
    start_urls = ['http://office.cps.zju.edu.cn/zytz_26502/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/zytz_26502/list%d.htm'


class PharmaceuticalCollegePage12Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page12'
    source = '34'
    publisher = '药学院'
    column = ['国际交流', '信息动态']
    start_urls = ['http://office.cps.zju.edu.cn/xxdt_26503/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/xxdt_26503/list%d.htm'


class PharmaceuticalCollegePage13Spider(PharmaceuticalCollegePage0Spider):
    name = 'pharmaceutical_college_page13'
    source = '34'
    publisher = '药学院'
    column = ['国际交流', '国际交流项目']
    start_urls = ['http://office.cps.zju.edu.cn/gjjlxm/list.htm']
    page_url = 'http://office.cps.zju.edu.cn/gjjlxm/list%d.htm'
