# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class PhysicsDepartPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'physics_depart_page0'
    source = '35'
    publisher = '物理学系'
    column = ['科学研究', '学术信息']
    start_urls = ['http://office.physics.zju.edu.cn/39158/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39158/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="art_list"]/li'
    title_xpath = './/a[@target="_blank"]/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './span/text()'
    publish_time_format = '[%Y-%m-%d]'
    publisher_group = '专业院系'


class PhysicsDepartPage1Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page1'
    source = '35'
    publisher = '物理学系'
    column = ['科学研究', '科研成果']
    start_urls = ['http://office.physics.zju.edu.cn/39159/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39159/list%d.htm'


class PhysicsDepartPage2Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page2'
    source = '35'
    publisher = '物理学系'
    column = ['科学研究', '科研项目']
    start_urls = ['http://office.physics.zju.edu.cn/39162/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39162/list%d.htm'


class PhysicsDepartPage3Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page3'
    source = '35'
    publisher = '物理学系'
    column = ['科学研究', '最新通知']
    start_urls = ['http://office.physics.zju.edu.cn/39131/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39131/list%d.htm'


class PhysicsDepartPage4Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page4'
    source = '35'
    publisher = '物理学系'
    column = ['本科生教育', '本科生科研项目']
    start_urls = ['http://office.physics.zju.edu.cn/39170/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39170/list%d.htm'


class PhysicsDepartPage5Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page5'
    source = '35'
    publisher = '物理学系'
    column = ['本科生教育', '服务指南', '办事指南']
    start_urls = ['http://office.physics.zju.edu.cn/39171/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39171/list%d.htm'


class PhysicsDepartPage6Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page6'
    source = '35'
    publisher = '物理学系'
    column = ['本科生教育', '服务指南', '各类文件']
    start_urls = ['http://office.physics.zju.edu.cn/39212/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39212/list%d.htm'


class PhysicsDepartPage7Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page7'
    source = '35'
    publisher = '物理学系'
    column = ['求是科学班', '招生信息']
    start_urls = ['http://office.physics.zju.edu.cn/39172/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39172/list%d.htm'


class PhysicsDepartPage8Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page8'
    source = '35'
    publisher = '物理学系'
    column = ['求是科学班', '毕业设计']
    start_urls = ['http://office.physics.zju.edu.cn/39173/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39173/list%d.htm'


class PhysicsDepartPage9Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page9'
    source = '35'
    publisher = '物理学系'
    column = ['求是科学班', '培养方案']
    start_urls = ['http://office.physics.zju.edu.cn/39218/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39218/list%d.htm'


class PhysicsDepartPage10Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page10'
    source = '35'
    publisher = '物理学系'
    column = ['求是科学班', '科研训练']
    start_urls = ['http://office.physics.zju.edu.cn/39219/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39219/list%d.htm'


class PhysicsDepartPage11Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page11'
    source = '35'
    publisher = '物理学系'
    column = ['学生思政', '本科生思政', '党建团建']
    start_urls = ['http://office.physics.zju.edu.cn/39240/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39240/list%d.htm'


class PhysicsDepartPage12Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page12'
    source = '35'
    publisher = '物理学系'
    column = ['学生思政', '本科生思政', '学生活动']
    start_urls = ['http://office.physics.zju.edu.cn/39241/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39241/list%d.htm'


class PhysicsDepartPage13Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page13'
    source = '35'
    publisher = '物理学系'
    column = ['学生思政', '本科生思政', '奖助学金']
    start_urls = ['http://office.physics.zju.edu.cn/39242/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39242/list%d.htm'


class PhysicsDepartPage14Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page14'
    source = '35'
    publisher = '物理学系'
    column = ['学生思政', '本科生思政', '就业信息']
    start_urls = ['http://office.physics.zju.edu.cn/39243/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39243/list%d.htm'


class PhysicsDepartPage15Spider(PhysicsDepartPage0Spider):
    name = 'physics_depart_page15'
    source = '35'
    publisher = '物理学系'
    column = ['学生思政', '下载专区']
    start_urls = ['http://office.physics.zju.edu.cn/39190/list.htm']
    page_url = 'http://office.physics.zju.edu.cn/39190/list%d.htm'
