# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class PolymerDepartPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'polymer_depart_page0'
    source = '36'
    publisher = '高分子科学与工程学系'
    column = ['本科生教育', '专业设置']
    start_urls = ['http://office.polymer.zju.edu.cn/zysz/list.htm']
    page_url = 'http://office.polymer.zju.edu.cn/zysz/list%d.htm'
    initial_page = 0
    list_xpath = '//div[@id="wp_news_w11"]/li[@class="list-item"]'
    title_xpath = './/div[@class="content"]//h3/@title'
    url_xpath = './a/@href'
    publish_time_xpath = './/p[@class="md"]/text()'
    publish_time_xpath_extra = './/div[@class="date fl"]/p[@class="year"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class PolymerDepartPage1Spider(PolymerDepartPage0Spider):
    name = 'polymer_depart_page1'
    source = '36'
    publisher = '高分子科学与工程学系'
    column = ['本科生教育', '实践教学']
    start_urls = ['http://office.polymer.zju.edu.cn/sjjx/list.htm']
    page_url = 'http://office.polymer.zju.edu.cn/sjjx/list%d.htm'


class PolymerDepartPage2Spider(PolymerDepartPage0Spider):
    name = 'polymer_depart_page2'
    source = '36'
    publisher = '高分子科学与工程学系'
    column = ['学生工作', '就业指导']
    start_urls = ['http://office.polymer.zju.edu.cn/jyzd/list.htm']
    page_url = 'http://office.polymer.zju.edu.cn/jyzd/list%d.htm'


class PolymerDepartPage3Spider(PolymerDepartPage0Spider):
    name = 'polymer_depart_page3'
    source = '36'
    publisher = '高分子科学与工程学系'
    column = ['学生工作', '系团委']
    start_urls = ['http://office.polymer.zju.edu.cn/xtw/list.htm']
    page_url = 'http://office.polymer.zju.edu.cn/xtw/list%d.htm'


class PolymerDepartPage4Spider(PolymerDepartPage0Spider):
    name = 'polymer_depart_page4'
    source = '36'
    publisher = '高分子科学与工程学系'
    column = ['学生工作', '学生会']
    start_urls = ['http://office.polymer.zju.edu.cn/xtw/list.htm']
    page_url = 'http://office.polymer.zju.edu.cn/xtw/list%d.htm'


class PolymerDepartPage5Spider(PolymerDepartPage0Spider):
    name = 'polymer_depart_page5'
    source = '36'
    publisher = '高分子科学与工程学系'
    column = ['学生工作', '就业信息']
    start_urls = ['http://office.polymer.zju.edu.cn/jyxx/list.htm']
    page_url = 'http://office.polymer.zju.edu.cn/jyxx/list%d.htm'


class PolymerDepartPage6Spider(PolymerDepartPage0Spider):
    name = 'polymer_depart_page6'
    source = '36'
    publisher = '高分子科学与工程学系'
    column = ['学生工作', '三助管理']
    start_urls = ['http://office.polymer.zju.edu.cn/szgl/list.htm']
    page_url = 'http://office.polymer.zju.edu.cn/szgl/list%d.htm'
