# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class PublicAffairsSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'public_affairs_school_page0'
    source = '38'
    publisher = '公共管理学院'
    column = ['本科生教育', '本科生事务', '制度文件']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/16807/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/16807/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@class="lbytb clearfix"]'
    title_xpath = './/a[2]/@title'
    url_xpath = './/a[2]/@href'
    publish_time_xpath = './div[@class="lbysj"]/text()'
    publish_time_format = '[%Y-%m-%d]'
    publisher_group = '专业院系'


class PublicAffairsSchoolPage1Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page1'
    source = '38'
    publisher = '公共管理学院'
    column = ['本科生教育', '本科生事务', '服务信息']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/16808/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/16808/list%d.htm'


class PublicAffairsSchoolPage2Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page2'
    source = '38'
    publisher = '公共管理学院'
    column = ['学生思政', '学生党建', '本科生党建']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14757/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14757/list%d.htm'


class PublicAffairsSchoolPage3Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page3'
    source = '38'
    publisher = '公共管理学院'
    column = ['学生思政', '学生团建']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14508/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14508/list%d.htm'


class PublicAffairsSchoolPage4Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page4'
    source = '38'
    publisher = '公共管理学院'
    column = ['学生思政', '学工事务']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14509/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14509/list%d.htm'


class PublicAffairsSchoolPage5Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page5'
    source = '38'
    publisher = '公共管理学院'
    column = ['学生思政', '就业指导']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14511/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14511/list%d.htm'


class PublicAffairsSchoolPage6Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page6'
    source = '38'
    publisher = '公共管理学院'
    column = ['学生思政', '评奖评优', '本科生']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14759/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14759/list%d.htm'


class PublicAffairsSchoolPage7Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page7'
    source = '38'
    publisher = '公共管理学院'
    column = ['学生思政', '心理资助', '本科生']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14761/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14761/list%d.htm'


class PublicAffairsSchoolPage8Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page8'
    source = '38'
    publisher = '公共管理学院'
    column = ['学生思政', '学生组织', '本科生']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14735/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14735/list%d.htm'


class PublicAffairsSchoolPage9Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page9'
    source = '38'
    publisher = '公共管理学院'
    column = ['学生思政', '表格下载', '党建']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/15129/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/15129/list%d.htm'


class PublicAffairsSchoolPage10Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page10'
    source = '38'
    publisher = '公共管理学院'
    column = ['国际事务', '通知公告']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14471/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14471/list%d.htm'


class PublicAffairsSchoolPage11Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page11'
    source = '38'
    publisher = '公共管理学院'
    column = ['国际事务', '学生交流']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14473/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14473/list%d.htm'


class PublicAffairsSchoolPage12Spider(PublicAffairsSchoolPage0Spider):
    name = 'public_affairs_school_page12'
    source = '38'
    publisher = '公共管理学院'
    column = ['国际事务', '服务信息']
    start_urls = ['http://www.spa.zju.edu.cn/spaoffice/14474/list.htm']
    page_url = 'http://www.spa.zju.edu.cn/spaoffice/14474/list%d.htm'
