# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class QiushiCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'qiushi_college_page0'
    source = '39'
    publisher = '求是学院'
    column = ['文件汇编', '党委文件']
    start_urls = ['http://qsxy.zju.edu.cn/30812/list.htm']
    page_url = 'http://qsxy.zju.edu.cn/30812/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="news_list list2"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './span[@class="news_meta"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '学校部门'


class QiushiCollegePage1Spider(QiushiCollegePage0Spider):
    name = 'qiushi_college_page1'
    source = '39'
    publisher = '求是学院'
    column = ['文件汇编', '教学教务相关文件']
    start_urls = ['http://qsxy.zju.edu.cn/30811/list.htm']
    page_url = 'http://qsxy.zju.edu.cn/30811/list%d.htm'


class QiushiCollegePage2Spider(QiushiCollegePage0Spider):
    name = 'qiushi_college_page2'
    source = '39'
    publisher = '求是学院'
    column = ['文件汇编', '学院制度建设']
    start_urls = ['http://qsxy.zju.edu.cn/30813/list.htm']
    page_url = 'http://qsxy.zju.edu.cn/30813/list%d.htm'


class QiushiCollegePage3Spider(QiushiCollegePage0Spider):
    name = 'qiushi_college_page3'
    source = '39'
    publisher = '求是学院'
    column = ['文件汇编', '学院年鉴']
    start_urls = ['http://qsxy.zju.edu.cn/xynj/list.htm']
    page_url = 'http://qsxy.zju.edu.cn/xynj/list%d.htm'
