version: '3.3'

# WARNING: This website contains sticky notices.
# Set max_sticky to some value in the generated spider.
# For details, see https://git.zjuqsc.com/notify/notify-scrapy/wikis/Sticky-Notices

name: biosystems_college
source: 6
publisher: 生物系统工程与食品科学学院
initial_page: 0
list_xpath: "//ul[@class=\"cg-news-list\"]/li"
title_xpath: ".//a/@title"
url_xpath: ".//a/@href"
publish_time_xpath: "./span/text()"
publish_time_format: "%Y-%m-%d"
pages_converter: and_page_equals
publisher_group: 专业院系
pages:
  首页:
    重点提示: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=54
    最新通知: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=55
  科学研究:
    通知信息: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1224
  党建工作:
    通知公告: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1219
    表格下载: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1223
  研究生教育:
    招生信息:
      博士生招生: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1439
      硕士生招生: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=31693
      推免生招生: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1438
      在职专业招生: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1440
  本科教育:
    日常信息: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=872
    专业设置: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=873
    培养方案: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=874
    教学研究: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=875
    科研训练: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=876
    实践教学: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=877
    表格下载: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=879
  思政就业:
    最新通知: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=28093
    学生党建:
      党员发展: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1263
      公示平台: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1262
      学习园地: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1264
    学工事务:
      评奖评优: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1274
      勤工助学与资助: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1275
      科研训练: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1276
      出国及其他: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=31502
    共青团:
      团委工作: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1272
      团学联: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1267
      社会实践: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1270
    心理健康:
      最新消息: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1285
    体育运动: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=30605
    竞赛与其他:
      各类竞赛: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=37153
      其他: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=37154
    工作职责: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=36408
  对外交流:
    工作通知: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1233
  就业服务:
    新闻通知:
      活动通知: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156209
    生涯规划:
      职业规划: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1281
      学长分享: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156213
      咨询预约: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=181599
    招聘咨询:
      专场宣讲信息: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156217
      综合招聘信息: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156219
      学院招聘信息: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156218
      重点单位介绍: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1280
    综合服务:
      毕业生生源与学科特色介绍: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156222
      历年查询: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1284
      表格下载: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1283
      常见问题指引: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156224
    就业引导:
      重点清单: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156226
      国企央企: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156227
      高校与科研院所: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156228
      选调生: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180310
      西部就业: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180311
      国际组织: http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180312