version: '3.3'

# WARNING: This website contains sticky notices.
# Set max_sticky to some value in the generated spider.
# For details, see https://git.zjuqsc.com/notify/notify-scrapy/wikis/Sticky-Notices

# WARNING: The spider need to be modified.

name: cse_college
source: 11
publisher: 控制科学与工程学院
initial_page: 0
list_xpath: "//div[@class=\"con1rm2 mg2\"]/ul/li"
title_xpath: ".//a/@title"
url_xpath: ".//a/@href"
publish_time_xpath: "./div[@class=\"con1rm2l xi20\"]/text()"
publish_time_format: " \\n\\r\\t\\t%Y-%m-%d"
pages_converter: and_page_equals
publisher_group: 专业院系
pages:
  党建工作:
    最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055823
    活动简讯: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055824
    学习园地: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055826
    党风党纪: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055827
    下载专区: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055828
  人事工作:
    最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1063014
    人事文件: http://www.cse.zju.edu.cn/redir.php?catalog_id=1063015
    招聘信息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1063017
  科研学术:
    最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055783
    科研政策: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055785
    科研项目: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055787
    成果奖励: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055786
    表格下载: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055788
    服务指南: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055789
    科技创新论坛: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055790
    视频论坛: http://www.cse.zju.edu.cn/redir.php?catalog_id=1115104
  本科生教育:
    最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055813
    招生消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055814
    培养方案: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055815
    文件汇编: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055816
    科研训练: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055817
    对外交流: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055818
    短学期: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055819
    毕业设计: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055820
    表格下载: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055821
  研究生教育:
    最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055842
    学位管理: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055843
    招生信息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055845
    文件汇编: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055848
    工程硕士:
      最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1076492
      下载服务: http://www.cse.zju.edu.cn/redir.php?catalog_id=1076494
    表格下载: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055850
    服务指南: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055851
    校企合作: http://www.cse.zju.edu.cn/redir.php?catalog_id=1134005
  学生思政:
    日常通告: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055856
    党建相关: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055855
    评奖评优: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055857
    勤工资助: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055857
    消息链接: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055863
    表格规范: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055862
    文件汇编: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055854
  就业指导:
    相关通知: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055865
    就业信息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055866
  对外交流:
    最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055867
    外事动态: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055868
    表格下载: http://www.cse.zju.edu.cn/redir.php?catalog_id=1055869
  党政综合:
    党政办:
      最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1057225
    实验室安全:
      信息公告: http://www.cse.zju.edu.cn/redir.php?catalog_id=1057653
      规章制度: http://www.cse.zju.edu.cn/redir.php?catalog_id=1057654
  大平台:
    最新消息: http://www.cse.zju.edu.cn/redir.php?catalog_id=1135089



















