version: '3.3'

# WARNING: This website contains sticky notices.
# Set max_sticky to some value in the generated spider.
# For details, see https://git.zjuqsc.com/notify/notify-scrapy/wikis/Sticky-Notices

name: earth_school
source: 13
publisher: 地球科学学院
initial_page: 0
list_xpath: "//div[@id=\"wp_news_w7\"]/li"
title_xpath: ".//a/@title"
url_xpath: ".//a/@href"
publish_time_xpath: ".//span/text()"
publish_time_format: "%Y-%m-%d"
pages_converter: list_dot_htm
publisher_group: 专业院系
pages:
  首页:
    通知公告:
      重要通知: http://gs.zju.edu.cn/34774/list.htm
      公示信息: http://gs.zju.edu.cn/gsxx/list.htm
  教育教学:
    本科生教育:
      信息公告: http://gs.zju.edu.cn/35081/list.htm
      培养方案: http://gs.zju.edu.cn/35083/list.htm
      政策文件: http://gs.zju.edu.cn/35086/list.htm
      下载专区: http://gs.zju.edu.cn/35087/list.htm
    研究生教育:
      研究生招生: http://gs.zju.edu.cn/35222/list.htm
  实验中心:
    中心动态: http://gs.zju.edu.cn/xxdt/list.htm
    大型仪器设备管理:
      大型仪器设备规章制度: http://gs.zju.edu.cn/35097/list.htm
      办事指南: http://gs.zju.edu.cn/40789/list.htm
      仪器设备列表: http://gs.zju.edu.cn/40790/list.htm
    实验室安全:
      安全知识: http://gs.zju.edu.cn/35136/list.htm
  学生工作:
    通知公告: http://gs.zju.edu.cn/35100/list.htm
    团学建设: http://gs.zju.edu.cn/35102/list.htm
    奖助贷补: http://gs.zju.edu.cn/35103/list.htm
    青马工程: http://gs.zju.edu.cn/35105/list.htm
    下载专区:
      团建下载: http://gs.zju.edu.cn/35139/list.htm
      奖助下载: http://gs.zju.edu.cn/35140/list.htm
      文件规章: http://gs.zju.edu.cn/35141/list.htm
      其他表格: http://gs.zju.edu.cn/35142/list.htm
  国际交流:
    通知公告: http://gs.zju.edu.cn/35109/list.htm
    规章制度: http://gs.zju.edu.cn/35111/list.htm
    交流项目: http://gs.zju.edu.cn/35113/list.htm
  就业指导:
    重点引导: http://gs.zju.edu.cn/jyyd/list.htm
    通知公告: http://gs.zju.edu.cn/35122/list.htm
    招聘信息:
      信息汇总: http://gs.zju.edu.cn/xxhz/list.htm
      党政机关: http://gs.zju.edu.cn/dzjgzp/list.htm
      企事业单位: http://gs.zju.edu.cn/35121/list.htm
    下载专区: http://gs.zju.edu.cn/35125/list.htm
  学院党建:
    学院党建: http://gs.zju.edu.cn/34765/list.htm
    理论学习: http://gs.zju.edu.cn/35132/list.htm
    学院纪检: http://gs.zju.edu.cn/35133/list.htm
    党建下载: http://gs.zju.edu.cn/35134/list.htm