version: '3.3'


# The server will return 500 but with proper content, ignore it by removing 500 from RETRY_HTTP_CODES.

name: materials_school
source: 28
publisher: 材料科学与工程学院
initial_page: 1
list_xpath: "//div[@id=\"wp_news_w6\"]/ul/li"
title_xpath: ".//a/@title"
url_xpath: ".//a/@href"
publish_time_xpath: ".//span[@class=\"news_meta\"]/text()"
publish_time_format: "%Y.%m.%d"
pages_converter: list_dot_htm
publisher_group: 专业院系
pages:
  最新通知:
    重点提示: https://mse.zju.edu.cn/51056/list.htm
    党政综合: https://mse.zju.edu.cn/51057/list.htm
    本科生教育: https://mse.zju.edu.cn/51058/list.htm
    国际交流: https://mse.zju.edu.cn/51060/list.htm
    学生工作: https://mse.zju.edu.cn/51062/list.htm
    实验室工作: https://mse.zju.edu.cn/51063/list.htm
    科研开发: https://mse.zju.edu.cn/51061/list.htm
  公告栏: https://mse.zju.edu.cn/50928/list.htm
  学术活动: https://mse.zju.edu.cn/50925/list.htm
  微结构大赛: http://mse.zju.edu.cn/50932/list.htm