version: '3.3'


name: optical_sci_college
source: 33
publisher: 光电科学与工程学院
initial_page: 1
list_xpath: "//div[@class="content-middle-list"]//td/div[1]//tr"
title_xpath: ".//a/@title"
url_xpath: ".//a/@href"
publish_time_xpath: "./td[3]/text()"
publish_time_format: "[%Y-%m-%d]"
pages_converter: list_dot_htm
publisher_group: 专业院系
pages:
  首页:
    本科生教学:
      日常通知: http://office.opt.zju.edu.cn/38204/list.htm
      教学资讯: http://office.opt.zju.edu.cn/38205/list.htm
      SRTP: http://office.opt.zju.edu.cn/38206/list.htm
      毕业设计: http://office.opt.zju.edu.cn/38207/list.htm
      文件下载: http://office.opt.zju.edu.cn/38208/list.htm
      管理文件: http://office.opt.zju.edu.cn/38209/list.htm
      信息查询: http://office.opt.zju.edu.cn/38210/list.htm
      本科生交流: http://office.opt.zju.edu.cn/38211/list.htm
    对外交流:
      本科生交流: http://office.opt.zju.edu.cn/38224/list.htm
    学生工作:
      日常信息: http://office.opt.zju.edu.cn/38230/list.htm
      学生党建: http://office.opt.zju.edu.cn/38231/list.htm
      团学联: http://office.opt.zju.edu.cn/38232/list.htm