# HTML Spider Generator version 3.1
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.
from datetime import datetime
from scrapy.loader import ItemLoader

from notify_scrapy.base_html_spider import BaseHTMLSpider
from notify_scrapy.items import NoticeItem


class GraduateSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.1'
    name = 'graduate_school_page0'
    source = '研究生院'
    publisher = '研究生院'
    column = ['教学管理']
    start_urls = ['http://grs.zju.edu.cn/redir.php?catalog_id=16313&tag=%E6%95%99%E5%AD%A6%E7%AE%A1%E7%90%86']
    page_url = 'http://grs.zju.edu.cn/redir.php?catalog_id=16313&tag=%E6%95%99%E5%AD%A6%E7%AE%A1%E7%90%86&page='
    initial_page = 0
    list_xpath = '//ul[@class="cg-pic-news-list"]/li'
    title_xpath = './h3/a/@title'
    url_xpath = './h3/a/@href'
    publish_time_xpath = './span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '学校部门'

    def parse(self, response):
        nodes = response.xpath(self.list_xpath)

        if len(nodes) == 0:
            return

        for node in nodes:
            loader = ItemLoader(item=NoticeItem(), selector=node)
            loader.add_xpath('title', self.title_xpath)
            loader.add_value('url', response.urljoin(node.xpath(self.url_xpath).extract_first()))
            pub_time_text = node.xpath(self.publish_time_xpath).extract_first()
            if pub_time_text:
                loader.add_value('publish_time', datetime.strptime(pub_time_text, self.publish_time_format))
            yield loader.load_item()
            if self.stop_signal:
                return

        self.page += 1
        yield response.follow(self.page_url + str(self.page), callback=self.parse)


class GraduateSchoolPage1Spider(GraduateSchoolPage0Spider):
    name = 'graduate_school_page1'
    source = '研究生院'
    publisher = '研究生院'
    column = ['各类资助']
    start_urls = ['http://grs.zju.edu.cn/redir.php?catalog_id=16313&tag=%E5%90%84%E7%B1%BB%E8%B5%84%E5%8A%A9']
    page_url = 'http://grs.zju.edu.cn/redir.php?catalog_id=16313&tag=%E5%90%84%E7%B1%BB%E8%B5%84%E5%8A%A9&page='


class GraduateSchoolPage2Spider(GraduateSchoolPage0Spider):
    name = 'graduate_school_page2'
    source = '研究生院'
    publisher = '研究生院'
    column = ['学科建设']
    start_urls = ['http://grs.zju.edu.cn/redir.php?catalog_id=16313&tag=%E5%AD%A6%E7%A7%91%E5%BB%BA%E8%AE%BE']
    page_url = 'http://grs.zju.edu.cn/redir.php?catalog_id=16313&tag=%E5%AD%A6%E7%A7%91%E5%BB%BA%E8%AE%BE&page='


class GraduateSchoolPage3Spider(GraduateSchoolPage0Spider):
    name = 'graduate_school_page3'
    source = '研究生院'
    publisher = '研究生院'
    column = ['海外交流']
    start_urls = ['http://grs.zju.edu.cn/redir.php?catalog_id=16313&tag=%E6%B5%B7%E5%A4%96%E4%BA%A4%E6%B5%81']
    page_url = 'http://grs.zju.edu.cn/redir.php?catalog_id=16313&tag=%E6%B5%B7%E5%A4%96%E4%BA%A4%E6%B5%81&page='
