# HTML Spider Generator version 3.1
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class PostgraduateWorkDepartPage0Spider(BaseHTMLSpider):
    generator_version = '3.1'
    name = 'postgraduate_work_depart_page0'
    source = '党委研究生工作部'
    publisher = '党委研究生工作部'
    column = ['通知公告']
    start_urls = ['http://ygb.zju.edu.cn/redir.php?catalog_id=140080']
    page_url = 'http://ygb.zju.edu.cn/redir.php?catalog_id=140080&page=%d'
    initial_page = 0
    list_xpath = '//ul[@class="common-news-list"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '学校部门'


class PostgraduateWorkDepartPage1Spider(PostgraduateWorkDepartPage0Spider):
    name = 'postgraduate_work_depart_page1'
    source = '党委研究生工作部'
    publisher = '党委研究生工作部'
    column = ['学籍管理']
    start_urls = ['http://ygb.zju.edu.cn/redir.php?catalog_id=140451']
    page_url = 'http://ygb.zju.edu.cn/redir.php?catalog_id=140451&page=%d'


class PostgraduateWorkDepartPage2Spider(PostgraduateWorkDepartPage0Spider):
    name = 'postgraduate_work_depart_page2'
    source = '党委研究生工作部'
    publisher = '党委研究生工作部'
    column = ['奖励资助']
    start_urls = ['http://ygb.zju.edu.cn/redir.php?catalog_id=140455']
    page_url = 'http://ygb.zju.edu.cn/redir.php?catalog_id=140455&page=%d'


class PostgraduateWorkDepartPage3Spider(PostgraduateWorkDepartPage0Spider):
    name = 'postgraduate_work_depart_page3'
    source = '党委研究生工作部'
    publisher = '党委研究生工作部'
    column = ['思政教育']
    start_urls = ['http://ygb.zju.edu.cn/redir.php?catalog_id=176393']
    page_url = 'http://ygb.zju.edu.cn/redir.php?catalog_id=176393&page=%d'


class PostgraduateWorkDepartPage4Spider(PostgraduateWorkDepartPage0Spider):
    name = 'postgraduate_work_depart_page4'
    source = '党委研究生工作部'
    publisher = '党委研究生工作部'
    column = ['实践教育']
    start_urls = ['http://ygb.zju.edu.cn/redir.php?catalog_id=140447']
    page_url = 'http://ygb.zju.edu.cn/redir.php?catalog_id=140447&page=%d'
