# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class AeronauticsSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'aeronautics_school_page0'
    source = '1'
    publisher = '航空航天学院'
    column = ['首页', '通知公告', '本科生教育']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=100']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=100&page=%d'
    initial_page = 0
    list_xpath = '//ul[@class="cg-news-list"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class AeronauticsSchoolPage1Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page1'
    source = '1'
    publisher = '航空航天学院'
    column = ['首页', '通知公告', '学生工作']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=105']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=105&page=%d'


class AeronauticsSchoolPage2Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page2'
    source = '1'
    publisher = '航空航天学院'
    column = ['首页', '会议室申请']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=34']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=34&page=%d'


class AeronauticsSchoolPage3Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page3'
    source = '1'
    publisher = '航空航天学院'
    column = ['首页', '学术讲座']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=12241']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=12241&page=%d'


class AeronauticsSchoolPage4Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page4'
    source = '1'
    publisher = '航空航天学院'
    column = ['本科生教育', '本科生招生']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=16']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=16&page=%d'


class AeronauticsSchoolPage5Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page5'
    source = '1'
    publisher = '航空航天学院'
    column = ['本科生教育', '本科生培养']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=17']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=17&page=%d'


class AeronauticsSchoolPage6Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page6'
    source = '1'
    publisher = '航空航天学院'
    column = ['本科生教育', '本科生就业']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=18']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=18&page=%d'


class AeronauticsSchoolPage7Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page7'
    source = '1'
    publisher = '航空航天学院'
    column = ['研究生教育', '研究生招生']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=19']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=19&page=%d'


class AeronauticsSchoolPage8Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page8'
    source = '1'
    publisher = '航空航天学院'
    column = ['对外交流', '交流活动']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=12163']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=12163&page=%d'


class AeronauticsSchoolPage9Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page9'
    source = '1'
    publisher = '航空航天学院'
    column = ['就业指导', '重点引导']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=105224']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=105224&page=%d'


class AeronauticsSchoolPage10Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page10'
    source = '1'
    publisher = '航空航天学院'
    column = ['就业指导', '通知公告']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=105225']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=105225&page=%d'


class AeronauticsSchoolPage11Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page11'
    source = '1'
    publisher = '航空航天学院'
    column = ['就业指导', '生涯规划', '生涯咨询']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=107248']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=107248&page=%d'


class AeronauticsSchoolPage12Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page12'
    source = '1'
    publisher = '航空航天学院'
    column = ['就业指导', '招聘信息']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=105227']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=105227&page=%d'


class AeronauticsSchoolPage13Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page13'
    source = '1'
    publisher = '航空航天学院'
    column = ['就业指导', '下载专区']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=105228']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=105228&page=%d'


class AeronauticsSchoolPage14Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page14'
    source = '1'
    publisher = '航空航天学院'
    column = ['就业指导', '办事指南']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=105230']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=105230&page=%d'


class AeronauticsSchoolPage15Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page15'
    source = '1'
    publisher = '航空航天学院'
    column = ['就业指导', '综合服务', '毕业生生源介绍']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=107253']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=107253&page=%d'


class AeronauticsSchoolPage16Spider(AeronauticsSchoolPage0Spider):
    name = 'aeronautics_school_page16'
    source = '1'
    publisher = '航空航天学院'
    column = ['就业指导', '综合服务', '常见问题指引']
    start_urls = ['http://saa.zju.edu.cn/redir.php?catalog_id=107255']
    page_url = 'http://saa.zju.edu.cn/redir.php?catalog_id=107255&page=%d'
