# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class AnimalCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'animal_college_page0'
    source = '3'
    publisher = '动物科学学院'
    column = ['网站首页', '全部']
    start_urls = ['http://office.cas.zju.edu.cn/qb/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/qb/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="news_list list2"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="news_meta"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class AnimalCollegePage1Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page1'
    source = '3'
    publisher = '动物科学学院'
    column = ['网站首页', '首页', '重点提示']
    start_urls = ['http://office.cas.zju.edu.cn/15048/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15048/list%d.htm'


class AnimalCollegePage2Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page2'
    source = '3'
    publisher = '动物科学学院'
    column = ['本科生教育', '实践竞赛', '实践教学']
    start_urls = ['http://office.cas.zju.edu.cn/16447/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/16447/list%d.htm'


class AnimalCollegePage3Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page3'
    source = '3'
    publisher = '动物科学学院'
    column = ['本科生教育', '实践竞赛', '科研训练']
    start_urls = ['http://office.cas.zju.edu.cn/16448/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/16448/list%d.htm'


class AnimalCollegePage4Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page4'
    source = '3'
    publisher = '动物科学学院'
    column = ['本科生教育', '课程建设']
    start_urls = ['http://office.cas.zju.edu.cn/15891/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15891/list%d.htm'


class AnimalCollegePage5Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page5'
    source = '3'
    publisher = '动物科学学院'
    column = ['本科生教育', '表格下载']
    start_urls = ['http://office.cas.zju.edu.cn/15892/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15892/list%d.htm'


class AnimalCollegePage6Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page6'
    source = '3'
    publisher = '动物科学学院'
    column = ['研究生教育', '招生专栏', '硕士生招生']
    start_urls = ['http://office.cas.zju.edu.cn/15965/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15965/list%d.htm'


class AnimalCollegePage7Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page7'
    source = '3'
    publisher = '动物科学学院'
    column = ['研究生教育', '招生专栏', '博士生招生']
    start_urls = ['http://office.cas.zju.edu.cn/15966/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15966/list%d.htm'


class AnimalCollegePage8Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page8'
    source = '3'
    publisher = '动物科学学院'
    column = ['学子在线', '学生党建']
    start_urls = ['http://office.cas.zju.edu.cn/15925/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15925/list%d.htm'


class AnimalCollegePage9Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page9'
    source = '3'
    publisher = '动物科学学院'
    column = ['学子在线', '团建工作']
    start_urls = ['http://office.cas.zju.edu.cn/15928/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15928/list%d.htm'


class AnimalCollegePage10Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page10'
    source = '3'
    publisher = '动物科学学院'
    column = ['学子在线', '本科生事务']
    start_urls = ['http://office.cas.zju.edu.cn/15926/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15926/list%d.htm'


class AnimalCollegePage11Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page11'
    source = '3'
    publisher = '动物科学学院'
    column = ['学子在线', '就业工作']
    start_urls = ['http://office.cas.zju.edu.cn/15929/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15929/list%d.htm'


class AnimalCollegePage12Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page12'
    source = '3'
    publisher = '动物科学学院'
    column = ['学子在线', '资料下载']
    start_urls = ['http://office.cas.zju.edu.cn/15930/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15930/list%d.htm'


class AnimalCollegePage13Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page13'
    source = '3'
    publisher = '动物科学学院'
    column = ['国际交流', '通知公告']
    start_urls = ['http://office.cas.zju.edu.cn/15893/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15893/list%d.htm'


class AnimalCollegePage14Spider(AnimalCollegePage0Spider):
    name = 'animal_college_page14'
    source = '3'
    publisher = '动物科学学院'
    column = ['国际交流', '交流项目', '本科生']
    start_urls = ['http://office.cas.zju.edu.cn/15898/list.htm']
    page_url = 'http://office.cas.zju.edu.cn/15898/list%d.htm'
