# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class ArchitectureCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'architecture_college_page0'
    source = '4'
    publisher = '建筑工程学院'
    column = ['首页', '重点提示']
    start_urls = ['http://www.ccea.zju.edu.cn/7969/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/7969/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w6"]/ul/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="news_meta"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class ArchitectureCollegePage1Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page1'
    source = '4'
    publisher = '建筑工程学院'
    column = ['首页', '学术信息']
    start_urls = ['http://www.ccea.zju.edu.cn/xsxx1/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/xsxx1/list%d.htm'


class ArchitectureCollegePage2Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page2'
    source = '4'
    publisher = '建筑工程学院'
    column = ['党政管理', '党务工作', '党务信息']
    start_urls = ['http://www.ccea.zju.edu.cn/dwxx/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/dwxx/list%d.htm'


class ArchitectureCollegePage3Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page3'
    source = '4'
    publisher = '建筑工程学院'
    column = ['党政管理', '党务工作', '专题教育']
    start_urls = ['http://www.ccea.zju.edu.cn/ztjy/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/ztjy/list%d.htm'


class ArchitectureCollegePage4Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page4'
    source = '4'
    publisher = '建筑工程学院'
    column = ['党政管理', '院务公开', '院务信息']
    start_urls = ['http://www.ccea.zju.edu.cn/ywxx/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/ywxx/list%d.htm'


class ArchitectureCollegePage5Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page5'
    source = '4'
    publisher = '建筑工程学院'
    column = ['教育教学', '最新消息']
    start_urls = ['http://www.ccea.zju.edu.cn/zxxx_23236/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/zxxx_23236/list%d.htm'


class ArchitectureCollegePage6Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page6'
    source = '4'
    publisher = '建筑工程学院'
    column = ['教育教学', '本科生教育', '教学教务']
    start_urls = ['http://www.ccea.zju.edu.cn/18410/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18410/list%d.htm'


class ArchitectureCollegePage7Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page7'
    source = '4'
    publisher = '建筑工程学院'
    column = ['教育教学', '本科生教育', '专业确认']
    start_urls = ['http://www.ccea.zju.edu.cn/18411/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18411/list%d.htm'


class ArchitectureCollegePage8Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page8'
    source = '4'
    publisher = '建筑工程学院'
    column = ['教育教学', '本科生教育', '推荐免试']
    start_urls = ['http://www.ccea.zju.edu.cn/18412/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18412/list%d.htm'


class ArchitectureCollegePage9Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page9'
    source = '4'
    publisher = '建筑工程学院'
    column = ['教育教学', '本科生教育', '科研训练']
    start_urls = ['http://www.ccea.zju.edu.cn/18413/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18413/list%d.htm'


class ArchitectureCollegePage10Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page10'
    source = '4'
    publisher = '建筑工程学院'
    column = ['教育教学', '本科生教育', '结构大赛']
    start_urls = ['http://www.ccea.zju.edu.cn/18414/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18414/list%d.htm'


class ArchitectureCollegePage11Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page11'
    source = '4'
    publisher = '建筑工程学院'
    column = ['教育教学', '实习信息']
    start_urls = ['http://www.ccea.zju.edu.cn/18409/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18409/list%d.htm'


class ArchitectureCollegePage12Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page12'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '最新消息']
    start_urls = ['http://www.ccea.zju.edu.cn/zxxx_23233/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/zxxx_23233/list%d.htm'


class ArchitectureCollegePage13Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page13'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '党团建设', '党建工作']
    start_urls = ['http://www.ccea.zju.edu.cn/18463/list1.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18463/list1list%d.htm'


class ArchitectureCollegePage14Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page14'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '党团建设', '团建工作']
    start_urls = ['http://www.ccea.zju.edu.cn/18464/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18464/list%d.htm'


class ArchitectureCollegePage15Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page15'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '学生事务', '评奖评优']
    start_urls = ['http://www.ccea.zju.edu.cn/19119/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19119/list%d.htm'


class ArchitectureCollegePage16Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page16'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '学生事务', '学生资助']
    start_urls = ['http://www.ccea.zju.edu.cn/19120/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19120/list%d.htm'


class ArchitectureCollegePage17Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page17'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '学生事务', '其他事务']
    start_urls = ['http://www.ccea.zju.edu.cn/qtsw/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/qtsw/list%d.htm'


class ArchitectureCollegePage18Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page18'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '实践创新', '实践创新']
    start_urls = ['http://www.ccea.zju.edu.cn/18460/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18460/list%d.htm'


class ArchitectureCollegePage19Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page19'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '实践创新', '学生科技']
    start_urls = ['http://www.ccea.zju.edu.cn/19123/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19123/list%d.htm'


class ArchitectureCollegePage20Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page20'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '实践创新', '素质拓展']
    start_urls = ['http://www.ccea.zju.edu.cn/19124/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19124/list%d.htm'


class ArchitectureCollegePage21Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page21'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '实践创新', '社会实践']
    start_urls = ['http://www.ccea.zju.edu.cn/19125/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19125/list%d.htm'


class ArchitectureCollegePage22Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page22'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '实践创新', '志愿服务']
    start_urls = ['http://www.ccea.zju.edu.cn/19126/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19126/list%d.htm'


class ArchitectureCollegePage23Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page23'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '学生组织', '学生会']
    start_urls = ['http://www.ccea.zju.edu.cn/19127/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19127/list%d.htm'


class ArchitectureCollegePage24Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page24'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '学生组织', '学生社团']
    start_urls = ['http://www.ccea.zju.edu.cn/19129/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19129/list%d.htm'


class ArchitectureCollegePage25Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page25'
    source = '4'
    publisher = '建筑工程学院'
    column = ['学生工作', '学生组织', '学生风采']
    start_urls = ['http://www.ccea.zju.edu.cn/19130/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/19130/list%d.htm'


class ArchitectureCollegePage26Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page26'
    source = '4'
    publisher = '建筑工程学院'
    column = ['国际交流', '国际交流']
    start_urls = ['http://www.ccea.zju.edu.cn/8024/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/8024/list%d.htm'


class ArchitectureCollegePage27Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page27'
    source = '4'
    publisher = '建筑工程学院'
    column = ['国际交流', '交流项目', '交流项目']
    start_urls = ['http://www.ccea.zju.edu.cn/8120/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/8120/list%d.htm'


class ArchitectureCollegePage28Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page28'
    source = '4'
    publisher = '建筑工程学院'
    column = ['国际交流', '交流项目', '【Go Global】']
    start_urls = ['http://www.ccea.zju.edu.cn/wwowwlobalwjzgcxygjsytzjlxm/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/wwowwlobalwjzgcxygjsytzjlxm/list%d.htm'


class ArchitectureCollegePage29Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page29'
    source = '4'
    publisher = '建筑工程学院'
    column = ['国际交流', '交流资助', '交流赞助']
    start_urls = ['http://www.ccea.zju.edu.cn/gpzz/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/gpzz/list%d.htm'


class ArchitectureCollegePage30Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page30'
    source = '4'
    publisher = '建筑工程学院'
    column = ['国际交流', '交流资助', '公派资助']
    start_urls = ['http://www.ccea.zju.edu.cn/12261/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/12261/list%d.htm'


class ArchitectureCollegePage31Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page31'
    source = '4'
    publisher = '建筑工程学院'
    column = ['国际交流', '交流资助', '会议资助']
    start_urls = ['http://www.ccea.zju.edu.cn/12262/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/12262/list%d.htm'


class ArchitectureCollegePage32Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page32'
    source = '4'
    publisher = '建筑工程学院'
    column = ['招生工作', '研究生招生']
    start_urls = ['http://www.ccea.zju.edu.cn/18473/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/18473/list%d.htm'


class ArchitectureCollegePage33Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page33'
    source = '4'
    publisher = '建筑工程学院'
    column = ['就业工作', '通知公告', '学院通知']
    start_urls = ['http://www.ccea.zju.edu.cn/xytz/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/xytz/list%d.htm'


class ArchitectureCollegePage34Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page34'
    source = '4'
    publisher = '建筑工程学院'
    column = ['就业工作', '通知公告', '宣讲会安排']
    start_urls = ['http://www.ccea.zju.edu.cn/xjhap/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/xjhap/list%d.htm'


class ArchitectureCollegePage35Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page35'
    source = '4'
    publisher = '建筑工程学院'
    column = ['就业工作', '通知公告', '招聘信息']
    start_urls = ['http://www.ccea.zju.edu.cn/zpxx/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/zpxx/list%d.htm'


class ArchitectureCollegePage36Spider(ArchitectureCollegePage0Spider):
    name = 'architecture_college_page36'
    source = '4'
    publisher = '建筑工程学院'
    column = ['就业工作', '通知公告', '公务员选调生公告']
    start_urls = ['http://www.ccea.zju.edu.cn/gwyxdsgg/list.htm']
    page_url = 'http://www.ccea.zju.edu.cn/gwyxdsgg/list%d.htm'
