# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class BiosystemsCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'biosystems_college_page0'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['首页', '重点提示']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=54']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=54&page=%d'
    initial_page = 0
    list_xpath = '//ul[@class="cg-news-list"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class BiosystemsCollegePage1Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page1'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['首页', '最新通知']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=55']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=55&page=%d'


class BiosystemsCollegePage2Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page2'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['科学研究', '通知信息']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1224']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1224&page=%d'


class BiosystemsCollegePage3Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page3'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['党建工作', '通知公告']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1219']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1219&page=%d'


class BiosystemsCollegePage4Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page4'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['党建工作', '表格下载']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1223']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1223&page=%d'


class BiosystemsCollegePage5Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page5'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['研究生教育', '招生信息', '博士生招生']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1439']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1439&page=%d'


class BiosystemsCollegePage6Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page6'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['研究生教育', '招生信息', '硕士生招生']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=31693']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=31693&page=%d'


class BiosystemsCollegePage7Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page7'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['研究生教育', '招生信息', '推免生招生']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1438']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1438&page=%d'


class BiosystemsCollegePage8Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page8'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['研究生教育', '招生信息', '在职专业招生']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1440']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1440&page=%d'


class BiosystemsCollegePage9Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page9'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['本科教育', '日常信息']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=872']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=872&page=%d'


class BiosystemsCollegePage10Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page10'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['本科教育', '专业设置']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=873']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=873&page=%d'


class BiosystemsCollegePage11Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page11'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['本科教育', '培养方案']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=874']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=874&page=%d'


class BiosystemsCollegePage12Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page12'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['本科教育', '教学研究']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=875']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=875&page=%d'


class BiosystemsCollegePage13Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page13'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['本科教育', '科研训练']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=876']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=876&page=%d'


class BiosystemsCollegePage14Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page14'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['本科教育', '实践教学']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=877']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=877&page=%d'


class BiosystemsCollegePage15Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page15'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['本科教育', '表格下载']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=879']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=879&page=%d'


class BiosystemsCollegePage16Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page16'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '最新通知']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=28093']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=28093&page=%d'


class BiosystemsCollegePage17Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page17'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '学生党建', '党员发展']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1263']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1263&page=%d'


class BiosystemsCollegePage18Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page18'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '学生党建', '公示平台']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1262']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1262&page=%d'


class BiosystemsCollegePage19Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page19'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '学生党建', '学习园地']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1264']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1264&page=%d'


class BiosystemsCollegePage20Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page20'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '学工事务', '评奖评优']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1274']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1274&page=%d'


class BiosystemsCollegePage21Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page21'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '学工事务', '勤工助学与资助']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1275']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1275&page=%d'


class BiosystemsCollegePage22Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page22'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '学工事务', '科研训练']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1276']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1276&page=%d'


class BiosystemsCollegePage23Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page23'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '学工事务', '出国及其他']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=31502']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=31502&page=%d'


class BiosystemsCollegePage24Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page24'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '共青团', '团委工作']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1272']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1272&page=%d'


class BiosystemsCollegePage25Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page25'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '共青团', '团学联']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1267']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1267&page=%d'


class BiosystemsCollegePage26Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page26'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '共青团', '社会实践']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1270']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1270&page=%d'


class BiosystemsCollegePage27Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page27'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '心理健康', '最新消息']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1285']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1285&page=%d'


class BiosystemsCollegePage28Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page28'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '体育运动']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=30605']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=30605&page=%d'


class BiosystemsCollegePage29Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page29'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '竞赛与其他', '各类竞赛']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=37153']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=37153&page=%d'


class BiosystemsCollegePage30Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page30'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '竞赛与其他', '其他']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=37154']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=37154&page=%d'


class BiosystemsCollegePage31Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page31'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['思政就业', '工作职责']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=36408']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=36408&page=%d'


class BiosystemsCollegePage32Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page32'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['对外交流', '工作通知']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1233']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1233&page=%d'


class BiosystemsCollegePage33Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page33'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '新闻通知', '活动通知']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156209']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156209&page=%d'


class BiosystemsCollegePage34Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page34'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '生涯规划', '职业规划']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1281']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1281&page=%d'


class BiosystemsCollegePage35Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page35'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '生涯规划', '学长分享']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156213']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156213&page=%d'


class BiosystemsCollegePage36Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page36'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '生涯规划', '咨询预约']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=181599']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=181599&page=%d'


class BiosystemsCollegePage37Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page37'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '招聘咨询', '专场宣讲信息']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156217']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156217&page=%d'


class BiosystemsCollegePage38Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page38'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '招聘咨询', '综合招聘信息']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156219']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156219&page=%d'


class BiosystemsCollegePage39Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page39'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '招聘咨询', '学院招聘信息']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156218']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156218&page=%d'


class BiosystemsCollegePage40Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page40'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '招聘咨询', '重点单位介绍']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1280']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1280&page=%d'


class BiosystemsCollegePage41Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page41'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '综合服务', '毕业生生源与学科特色介绍']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156222']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156222&page=%d'


class BiosystemsCollegePage42Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page42'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '综合服务', '历年查询']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1284']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1284&page=%d'


class BiosystemsCollegePage43Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page43'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '综合服务', '表格下载']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1283']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=1283&page=%d'


class BiosystemsCollegePage44Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page44'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '综合服务', '常见问题指引']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156224']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156224&page=%d'


class BiosystemsCollegePage45Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page45'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '就业引导', '重点清单']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156226']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156226&page=%d'


class BiosystemsCollegePage46Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page46'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '就业引导', '国企央企']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156227']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156227&page=%d'


class BiosystemsCollegePage47Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page47'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '就业引导', '高校与科研院所']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156228']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=156228&page=%d'


class BiosystemsCollegePage48Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page48'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '就业引导', '选调生']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180310']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180310&page=%d'


class BiosystemsCollegePage49Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page49'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '就业引导', '西部就业']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180311']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180311&page=%d'


class BiosystemsCollegePage50Spider(BiosystemsCollegePage0Spider):
    name = 'biosystems_college_page50'
    source = '6'
    publisher = '生物系统工程与食品科学学院'
    column = ['就业服务', '就业引导', '国际组织']
    start_urls = ['http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180312']
    page_url = 'http://www.caefs.zju.edu.cn/office/redir.php?catalog_id=180312&page=%d'
