# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class ChemistryDepartPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'chemistry_depart_page0'
    source = '8'
    publisher = '化学系'
    column = ['首页', '通知公告']
    start_urls = ['http://office.chem.zju.edu.cn/tz/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/tz/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w12"]/li'
    title_xpath = './/span[@class="item"]/text()'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="date"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class ChemistryDepartPage1Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page1'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '信息公告']
    start_urls = ['http://office.chem.zju.edu.cn/bksjy/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/bksjy/list%d.htm'


class ChemistryDepartPage2Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page2'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '办事指南']
    start_urls = ['http://office.chem.zju.edu.cn/55181/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/55181/list%d.htm'


class ChemistryDepartPage3Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page3'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '专业确认']
    start_urls = ['http://office.chem.zju.edu.cn/55182/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/55182/list%d.htm'


class ChemistryDepartPage4Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page4'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '保研免推']
    start_urls = ['http://office.chem.zju.edu.cn/55183/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/55183/list%d.htm'


class ChemistryDepartPage5Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page5'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '毕业论文']
    start_urls = ['http://office.chem.zju.edu.cn/34485/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34485/list%d.htm'


class ChemistryDepartPage6Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page6'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '实践竞赛']
    start_urls = ['http://office.chem.zju.edu.cn/55184/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/55184/list%d.htm'


class ChemistryDepartPage7Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page7'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '文件汇编']
    start_urls = ['http://office.chem.zju.edu.cn/55185/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/55185/list%d.htm'


class ChemistryDepartPage8Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page8'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '培养方案']
    start_urls = ['http://office.chem.zju.edu.cn/34486/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34486/list%d.htm'


class ChemistryDepartPage9Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page9'
    source = '8'
    publisher = '化学系'
    column = ['本科生教育', '资料下载']
    start_urls = ['http://office.chem.zju.edu.cn/zlxz_55186/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/zlxz_55186/list%d.htm'


class ChemistryDepartPage10Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page10'
    source = '8'
    publisher = '化学系'
    column = ['研究生教育', '招生专栏']
    start_urls = ['http://office.chem.zju.edu.cn/34491/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34491/list%d.htm'


class ChemistryDepartPage11Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page11'
    source = '8'
    publisher = '化学系'
    column = ['科学研究', '公示公告']
    start_urls = ['http://office.chem.zju.edu.cn/kxyj/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/kxyj/list%d.htm'


class ChemistryDepartPage12Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page12'
    source = '8'
    publisher = '化学系'
    column = ['科学研究', '科研文件']
    start_urls = ['http://office.chem.zju.edu.cn/34496/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34496/list%d.htm'


class ChemistryDepartPage13Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page13'
    source = '8'
    publisher = '化学系'
    column = ['国际交流', '公示公告']
    start_urls = ['http://office.chem.zju.edu.cn/34489/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34489/list%d.htm'


class ChemistryDepartPage14Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page14'
    source = '8'
    publisher = '化学系'
    column = ['国际交流', '交流项目']
    start_urls = ['http://office.chem.zju.edu.cn/55195/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/55195/list%d.htm'


class ChemistryDepartPage15Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page15'
    source = '8'
    publisher = '化学系'
    column = ['学生工作', '信息公告']
    start_urls = ['http://office.chem.zju.edu.cn/xgtw/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/xgtw/list%d.htm'


class ChemistryDepartPage16Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page16'
    source = '8'
    publisher = '化学系'
    column = ['学生工作', '团建园地']
    start_urls = ['http://office.chem.zju.edu.cn/34508/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34508/list%d.htm'


class ChemistryDepartPage17Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page17'
    source = '8'
    publisher = '化学系'
    column = ['学生工作', '奖助学金']
    start_urls = ['http://office.chem.zju.edu.cn/34510/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34510/list%d.htm'


class ChemistryDepartPage18Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page18'
    source = '8'
    publisher = '化学系'
    column = ['就业服务', '通知公告']
    start_urls = ['http://office.chem.zju.edu.cn/jyxx/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/jyxx/list%d.htm'


class ChemistryDepartPage19Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page19'
    source = '8'
    publisher = '化学系'
    column = ['就业服务', '重点引导']
    start_urls = ['http://office.chem.zju.edu.cn/52030/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/52030/list%d.htm'


class ChemistryDepartPage20Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page20'
    source = '8'
    publisher = '化学系'
    column = ['就业服务', '招聘信息']
    start_urls = ['http://office.chem.zju.edu.cn/zzrsdzcps/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/zzrsdzcps/list%d.htm'


class ChemistryDepartPage21Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page21'
    source = '8'
    publisher = '化学系'
    column = ['就业服务', '生涯规划', '经验分享']
    start_urls = ['http://office.chem.zju.edu.cn/jywfx/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/jywfx/list%d.htm'


class ChemistryDepartPage22Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page22'
    source = '8'
    publisher = '化学系'
    column = ['党员之家', '信息公告', '信息公告']
    start_urls = ['http://office.chem.zju.edu.cn/53455/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/53455/list%d.htm'


class ChemistryDepartPage23Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page23'
    source = '8'
    publisher = '化学系'
    column = ['党员之家', '信息公告', '公示公告']
    start_urls = ['http://office.chem.zju.edu.cn/53461/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/53461/list%d.htm'


class ChemistryDepartPage24Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page24'
    source = '8'
    publisher = '化学系'
    column = ['党员之家', '学习园地']
    start_urls = ['http://office.chem.zju.edu.cn/53457/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/53457/list%d.htm'


class ChemistryDepartPage25Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page25'
    source = '8'
    publisher = '化学系'
    column = ['实验室管理', '信息公告']
    start_urls = ['http://office.chem.zju.edu.cn/34516/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34516/list%d.htm'


class ChemistryDepartPage26Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page26'
    source = '8'
    publisher = '化学系'
    column = ['实验室管理', '办事指南']
    start_urls = ['http://office.chem.zju.edu.cn/bslc/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/bslc/list%d.htm'


class ChemistryDepartPage27Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page27'
    source = '8'
    publisher = '化学系'
    column = ['实验室管理', '安全教育']
    start_urls = ['http://office.chem.zju.edu.cn/34517/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34517/list%d.htm'


class ChemistryDepartPage28Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page28'
    source = '8'
    publisher = '化学系'
    column = ['实验室管理', '规章制度']
    start_urls = ['http://office.chem.zju.edu.cn/34518/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/34518/list%d.htm'


class ChemistryDepartPage29Spider(ChemistryDepartPage0Spider):
    name = 'chemistry_depart_page29'
    source = '8'
    publisher = '化学系'
    column = ['实验室管理', '资料下载']
    start_urls = ['http://office.chem.zju.edu.cn/bgxz/list.htm']
    page_url = 'http://office.chem.zju.edu.cn/bgxz/list%d.htm'
