# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class ChuKochenHonorsCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'chu_kochen_honors_college_page0'
    source = '9'
    publisher = '竺可桢学院'
    column = ['人才培养', '培养方案']
    start_urls = ['http://office.ckc.zju.edu.cn/34977/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34977/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="news_list list2"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="news_meta"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '学院行政'


class ChuKochenHonorsCollegePage1Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page1'
    source = '9'
    publisher = '竺可桢学院'
    column = ['招生选拔', '新生选拔']
    start_urls = ['http://office.ckc.zju.edu.cn/34975/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34975/list%d.htm'


class ChuKochenHonorsCollegePage2Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page2'
    source = '9'
    publisher = '竺可桢学院'
    column = ['招生选拔', '二次选拔']
    start_urls = ['http://office.ckc.zju.edu.cn/ecxb/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/ecxb/list%d.htm'


class ChuKochenHonorsCollegePage3Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page3'
    source = '9'
    publisher = '竺可桢学院'
    column = ['招生选拔', '交叉复合班选拔']
    start_urls = ['http://office.ckc.zju.edu.cn/jcfhbxb/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/jcfhbxb/list%d.htm'


class ChuKochenHonorsCollegePage4Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page4'
    source = '9'
    publisher = '竺可桢学院'
    column = ['教学教务', '工作通知']
    start_urls = ['http://office.ckc.zju.edu.cn/gztz/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/gztz/list%d.htm'


class ChuKochenHonorsCollegePage5Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page5'
    source = '9'
    publisher = '竺可桢学院'
    column = ['教学教务', '学生下载专区']
    start_urls = ['http://office.ckc.zju.edu.cn/34981/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34981/list%d.htm'


class ChuKochenHonorsCollegePage6Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page6'
    source = '9'
    publisher = '竺可桢学院'
    column = ['国际交流与合作', '活动通知']
    start_urls = ['http://office.ckc.zju.edu.cn/54298/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/54298/list%d.htm'


class ChuKochenHonorsCollegePage7Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page7'
    source = '9'
    publisher = '竺可桢学院'
    column = ['国际交流与合作', '海外科研实习项目']
    start_urls = ['http://office.ckc.zju.edu.cn/hwkysxxm/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/hwkysxxm/list%d.htm'


class ChuKochenHonorsCollegePage8Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page8'
    source = '9'
    publisher = '竺可桢学院'
    column = ['发展联络', '院友资讯']
    start_urls = ['http://office.ckc.zju.edu.cn/54301/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/54301/list%d.htm'


class ChuKochenHonorsCollegePage9Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page9'
    source = '9'
    publisher = '竺可桢学院'
    column = ['发展联络', '院友活动']
    start_urls = ['http://office.ckc.zju.edu.cn/54302/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/54302/list%d.htm'


class ChuKochenHonorsCollegePage10Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page10'
    source = '9'
    publisher = '竺可桢学院'
    column = ['学生事务', '最新通知']
    start_urls = ['http://office.ckc.zju.edu.cn/zxtz/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/zxtz/list%d.htm'


class ChuKochenHonorsCollegePage11Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page11'
    source = '9'
    publisher = '竺可桢学院'
    column = ['学生事务', '评奖评优']
    start_urls = ['http://office.ckc.zju.edu.cn/34986/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34986/list%d.htm'


class ChuKochenHonorsCollegePage12Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page12'
    source = '9'
    publisher = '竺可桢学院'
    column = ['学生事务', '勤工助学']
    start_urls = ['http://office.ckc.zju.edu.cn/34987/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34987/list%d.htm'


class ChuKochenHonorsCollegePage13Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page13'
    source = '9'
    publisher = '竺可桢学院'
    column = ['学生事务', '困难资助']
    start_urls = ['http://office.ckc.zju.edu.cn/34989/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34989/list%d.htm'


class ChuKochenHonorsCollegePage14Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page14'
    source = '9'
    publisher = '竺可桢学院'
    column = ['学生事务', '心理教育']
    start_urls = ['http://office.ckc.zju.edu.cn/34988/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34988/list%d.htm'


class ChuKochenHonorsCollegePage15Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page15'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '最新通知']
    start_urls = ['http://office.ckc.zju.edu.cn/34994/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34994/list%d.htm'


class ChuKochenHonorsCollegePage16Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page16'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生党建']
    start_urls = ['http://office.ckc.zju.edu.cn/34995/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34995/list%d.htm'


class ChuKochenHonorsCollegePage17Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page17'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '办公室']
    start_urls = ['http://office.ckc.zju.edu.cn/35235/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/35235/list%d.htm'


class ChuKochenHonorsCollegePage18Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page18'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '组织部']
    start_urls = ['http://office.ckc.zju.edu.cn/35236/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/35236/list%d.htm'


class ChuKochenHonorsCollegePage19Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page19'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '学研部']
    start_urls = ['http://office.ckc.zju.edu.cn/35237/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/35237/list%d.htm'


class ChuKochenHonorsCollegePage20Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page20'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '青志部']
    start_urls = ['http://office.ckc.zju.edu.cn/35238/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/35238/list%d.htm'


class ChuKochenHonorsCollegePage21Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page21'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '社实部']
    start_urls = ['http://office.ckc.zju.edu.cn/ssb/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/ssb/list%d.htm'


class ChuKochenHonorsCollegePage22Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page22'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '素测部']
    start_urls = ['http://office.ckc.zju.edu.cn/35239/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/35239/list%d.htm'


class ChuKochenHonorsCollegePage23Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page23'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '宣传部']
    start_urls = ['http://office.ckc.zju.edu.cn/35240/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/35240/list%d.htm'


class ChuKochenHonorsCollegePage24Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page24'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '班团风采']
    start_urls = ['http://office.ckc.zju.edu.cn/35241/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/35241/list%d.htm'


class ChuKochenHonorsCollegePage25Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page25'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生团建', '军训专栏']
    start_urls = ['http://office.ckc.zju.edu.cn/jxzl/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/jxzl/list%d.htm'


class ChuKochenHonorsCollegePage26Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page26'
    source = '9'
    publisher = '竺可桢学院'
    column = ['党团建设', '学生会']
    start_urls = ['http://office.ckc.zju.edu.cn/34997/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/34997/list%d.htm'


class ChuKochenHonorsCollegePage27Spider(ChuKochenHonorsCollegePage0Spider):
    name = 'chu_kochen_honors_college_page27'
    source = '9'
    publisher = '竺可桢学院'
    column = ['文件汇编', '学院文件']
    start_urls = ['http://office.ckc.zju.edu.cn/35002/list.htm']
    page_url = 'http://office.ckc.zju.edu.cn/35002/list%d.htm'
