# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class DanqingCommunityPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'danqing_community_page0'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['首页', '最新通知']
    start_urls = ['http://dqxy.zju.edu.cn/51432/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51432/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="news_list list2"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="news_meta"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '学园行政'


class DanqingCommunityPage1Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page1'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['首页', '公示公告']
    start_urls = ['http://dqxy.zju.edu.cn/51446/list.psp']
    page_url = 'http://dqxy.zju.edu.cn/51446/list.psplist%d.htm'


class DanqingCommunityPage2Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page2'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['首页', '活动预告']
    start_urls = ['http://dqxy.zju.edu.cn/51434/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51434/list%d.htm'


class DanqingCommunityPage3Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page3'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['党建园地', '党建园地']
    start_urls = ['http://dqxy.zju.edu.cn/51441/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51441/list%d.htm'


class DanqingCommunityPage4Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page4'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['党建园地', '最新通知']
    start_urls = ['http://dqxy.zju.edu.cn/51453/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51453/list%d.htm'


class DanqingCommunityPage5Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page5'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['团学园地', '最新通知']
    start_urls = ['http://dqxy.zju.edu.cn/51457/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51457/list%d.htm'


class DanqingCommunityPage6Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page6'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['团学园地', '基础团务']
    start_urls = ['http://dqxy.zju.edu.cn/51458/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51458/list%d.htm'


class DanqingCommunityPage7Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page7'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['团学园地', '青年志愿者']
    start_urls = ['http://dqxy.zju.edu.cn/51459/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51459/list%d.htm'


class DanqingCommunityPage8Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page8'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['团学园地', '社会实践']
    start_urls = ['http://dqxy.zju.edu.cn/51460/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51460/list%d.htm'


class DanqingCommunityPage9Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page9'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['团学园地', '素质拓展']
    start_urls = ['http://dqxy.zju.edu.cn/51461/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51461/list%d.htm'


class DanqingCommunityPage10Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page10'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['团学园地', '学生活动']
    start_urls = ['http://dqxy.zju.edu.cn/51462/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51462/list%d.htm'


class DanqingCommunityPage11Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page11'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学业园地', '最新通知']
    start_urls = ['http://dqxy.zju.edu.cn/51429/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51429/list%d.htm'


class DanqingCommunityPage12Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page12'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学业园地', '教务管理']
    start_urls = ['http://dqxy.zju.edu.cn/51464/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51464/list%d.htm'


class DanqingCommunityPage13Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page13'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学业园地', '学业辅导']
    start_urls = ['http://dqxy.zju.edu.cn/51465/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51465/list%d.htm'


class DanqingCommunityPage14Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page14'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学业园地', '生涯规划']
    start_urls = ['http://dqxy.zju.edu.cn/51466/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51466/list%d.htm'


class DanqingCommunityPage15Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page15'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学生事务', '学生事务']
    start_urls = ['http://dqxy.zju.edu.cn/51430/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51430/list%d.htm'


class DanqingCommunityPage16Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page16'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学生事务', '最新通知']
    start_urls = ['http://dqxy.zju.edu.cn/51467/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51467/list%d.htm'


class DanqingCommunityPage17Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page17'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学生事务', '评奖评优']
    start_urls = ['http://dqxy.zju.edu.cn/51468/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51468/list%d.htm'


class DanqingCommunityPage18Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page18'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学生事务', '学生资助']
    start_urls = ['http://dqxy.zju.edu.cn/51469/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51469/list%d.htm'


class DanqingCommunityPage19Spider(DanqingCommunityPage0Spider):
    name = 'danqing_community_page19'
    source = '12'
    publisher = '丹阳青溪学园'
    column = ['学生事务', '心理健康']
    start_urls = ['http://dqxy.zju.edu.cn/51471/list.htm']
    page_url = 'http://dqxy.zju.edu.cn/51471/list%d.htm'
