# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class EarthSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'earth_school_page0'
    source = '13'
    publisher = '地球科学学院'
    column = ['首页', '通知公告', '重要通知']
    start_urls = ['http://gs.zju.edu.cn/34774/list.htm']
    page_url = 'http://gs.zju.edu.cn/34774/list%d.htm'
    initial_page = 0
    list_xpath = '//div[@id="wp_news_w7"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class EarthSchoolPage1Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page1'
    source = '13'
    publisher = '地球科学学院'
    column = ['首页', '通知公告', '公示信息']
    start_urls = ['http://gs.zju.edu.cn/gsxx/list.htm']
    page_url = 'http://gs.zju.edu.cn/gsxx/list%d.htm'


class EarthSchoolPage2Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page2'
    source = '13'
    publisher = '地球科学学院'
    column = ['教育教学', '本科生教育', '信息公告']
    start_urls = ['http://gs.zju.edu.cn/35081/list.htm']
    page_url = 'http://gs.zju.edu.cn/35081/list%d.htm'


class EarthSchoolPage3Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page3'
    source = '13'
    publisher = '地球科学学院'
    column = ['教育教学', '本科生教育', '培养方案']
    start_urls = ['http://gs.zju.edu.cn/35083/list.htm']
    page_url = 'http://gs.zju.edu.cn/35083/list%d.htm'


class EarthSchoolPage4Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page4'
    source = '13'
    publisher = '地球科学学院'
    column = ['教育教学', '本科生教育', '政策文件']
    start_urls = ['http://gs.zju.edu.cn/35086/list.htm']
    page_url = 'http://gs.zju.edu.cn/35086/list%d.htm'


class EarthSchoolPage5Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page5'
    source = '13'
    publisher = '地球科学学院'
    column = ['教育教学', '本科生教育', '下载专区']
    start_urls = ['http://gs.zju.edu.cn/35087/list.htm']
    page_url = 'http://gs.zju.edu.cn/35087/list%d.htm'


class EarthSchoolPage6Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page6'
    source = '13'
    publisher = '地球科学学院'
    column = ['教育教学', '研究生教育', '研究生招生']
    start_urls = ['http://gs.zju.edu.cn/35222/list.htm']
    page_url = 'http://gs.zju.edu.cn/35222/list%d.htm'


class EarthSchoolPage7Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page7'
    source = '13'
    publisher = '地球科学学院'
    column = ['实验中心', '中心动态']
    start_urls = ['http://gs.zju.edu.cn/xxdt/list.htm']
    page_url = 'http://gs.zju.edu.cn/xxdt/list%d.htm'


class EarthSchoolPage8Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page8'
    source = '13'
    publisher = '地球科学学院'
    column = ['实验中心', '大型仪器设备管理', '大型仪器设备规章制度']
    start_urls = ['http://gs.zju.edu.cn/35097/list.htm']
    page_url = 'http://gs.zju.edu.cn/35097/list%d.htm'


class EarthSchoolPage9Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page9'
    source = '13'
    publisher = '地球科学学院'
    column = ['实验中心', '大型仪器设备管理', '办事指南']
    start_urls = ['http://gs.zju.edu.cn/40789/list.htm']
    page_url = 'http://gs.zju.edu.cn/40789/list%d.htm'


class EarthSchoolPage10Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page10'
    source = '13'
    publisher = '地球科学学院'
    column = ['实验中心', '大型仪器设备管理', '仪器设备列表']
    start_urls = ['http://gs.zju.edu.cn/40790/list.htm']
    page_url = 'http://gs.zju.edu.cn/40790/list%d.htm'


class EarthSchoolPage11Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page11'
    source = '13'
    publisher = '地球科学学院'
    column = ['实验中心', '实验室安全', '安全知识']
    start_urls = ['http://gs.zju.edu.cn/35136/list.htm']
    page_url = 'http://gs.zju.edu.cn/35136/list%d.htm'


class EarthSchoolPage12Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page12'
    source = '13'
    publisher = '地球科学学院'
    column = ['学生工作', '通知公告']
    start_urls = ['http://gs.zju.edu.cn/35100/list.htm']
    page_url = 'http://gs.zju.edu.cn/35100/list%d.htm'


class EarthSchoolPage13Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page13'
    source = '13'
    publisher = '地球科学学院'
    column = ['学生工作', '团学建设']
    start_urls = ['http://gs.zju.edu.cn/35102/list.htm']
    page_url = 'http://gs.zju.edu.cn/35102/list%d.htm'


class EarthSchoolPage14Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page14'
    source = '13'
    publisher = '地球科学学院'
    column = ['学生工作', '奖助贷补']
    start_urls = ['http://gs.zju.edu.cn/35103/list.htm']
    page_url = 'http://gs.zju.edu.cn/35103/list%d.htm'


class EarthSchoolPage15Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page15'
    source = '13'
    publisher = '地球科学学院'
    column = ['学生工作', '青马工程']
    start_urls = ['http://gs.zju.edu.cn/35105/list.htm']
    page_url = 'http://gs.zju.edu.cn/35105/list%d.htm'


class EarthSchoolPage16Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page16'
    source = '13'
    publisher = '地球科学学院'
    column = ['学生工作', '下载专区', '团建下载']
    start_urls = ['http://gs.zju.edu.cn/35139/list.htm']
    page_url = 'http://gs.zju.edu.cn/35139/list%d.htm'


class EarthSchoolPage17Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page17'
    source = '13'
    publisher = '地球科学学院'
    column = ['学生工作', '下载专区', '奖助下载']
    start_urls = ['http://gs.zju.edu.cn/35140/list.htm']
    page_url = 'http://gs.zju.edu.cn/35140/list%d.htm'


class EarthSchoolPage18Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page18'
    source = '13'
    publisher = '地球科学学院'
    column = ['学生工作', '下载专区', '文件规章']
    start_urls = ['http://gs.zju.edu.cn/35141/list.htm']
    page_url = 'http://gs.zju.edu.cn/35141/list%d.htm'


class EarthSchoolPage19Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page19'
    source = '13'
    publisher = '地球科学学院'
    column = ['学生工作', '下载专区', '其他表格']
    start_urls = ['http://gs.zju.edu.cn/35142/list.htm']
    page_url = 'http://gs.zju.edu.cn/35142/list%d.htm'


class EarthSchoolPage20Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page20'
    source = '13'
    publisher = '地球科学学院'
    column = ['国际交流', '通知公告']
    start_urls = ['http://gs.zju.edu.cn/35109/list.htm']
    page_url = 'http://gs.zju.edu.cn/35109/list%d.htm'


class EarthSchoolPage21Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page21'
    source = '13'
    publisher = '地球科学学院'
    column = ['国际交流', '规章制度']
    start_urls = ['http://gs.zju.edu.cn/35111/list.htm']
    page_url = 'http://gs.zju.edu.cn/35111/list%d.htm'


class EarthSchoolPage22Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page22'
    source = '13'
    publisher = '地球科学学院'
    column = ['国际交流', '交流项目']
    start_urls = ['http://gs.zju.edu.cn/35113/list.htm']
    page_url = 'http://gs.zju.edu.cn/35113/list%d.htm'


class EarthSchoolPage23Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page23'
    source = '13'
    publisher = '地球科学学院'
    column = ['就业指导', '重点引导']
    start_urls = ['http://gs.zju.edu.cn/jyyd/list.htm']
    page_url = 'http://gs.zju.edu.cn/jyyd/list%d.htm'


class EarthSchoolPage24Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page24'
    source = '13'
    publisher = '地球科学学院'
    column = ['就业指导', '通知公告']
    start_urls = ['http://gs.zju.edu.cn/35122/list.htm']
    page_url = 'http://gs.zju.edu.cn/35122/list%d.htm'


class EarthSchoolPage25Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page25'
    source = '13'
    publisher = '地球科学学院'
    column = ['就业指导', '招聘信息', '信息汇总']
    start_urls = ['http://gs.zju.edu.cn/xxhz/list.htm']
    page_url = 'http://gs.zju.edu.cn/xxhz/list%d.htm'


class EarthSchoolPage26Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page26'
    source = '13'
    publisher = '地球科学学院'
    column = ['就业指导', '招聘信息', '党政机关']
    start_urls = ['http://gs.zju.edu.cn/dzjgzp/list.htm']
    page_url = 'http://gs.zju.edu.cn/dzjgzp/list%d.htm'


class EarthSchoolPage27Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page27'
    source = '13'
    publisher = '地球科学学院'
    column = ['就业指导', '招聘信息', '企事业单位']
    start_urls = ['http://gs.zju.edu.cn/35121/list.htm']
    page_url = 'http://gs.zju.edu.cn/35121/list%d.htm'


class EarthSchoolPage28Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page28'
    source = '13'
    publisher = '地球科学学院'
    column = ['就业指导', '下载专区']
    start_urls = ['http://gs.zju.edu.cn/35125/list.htm']
    page_url = 'http://gs.zju.edu.cn/35125/list%d.htm'


class EarthSchoolPage29Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page29'
    source = '13'
    publisher = '地球科学学院'
    column = ['学院党建', '学院党建']
    start_urls = ['http://gs.zju.edu.cn/34765/list.htm']
    page_url = 'http://gs.zju.edu.cn/34765/list%d.htm'


class EarthSchoolPage30Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page30'
    source = '13'
    publisher = '地球科学学院'
    column = ['学院党建', '理论学习']
    start_urls = ['http://gs.zju.edu.cn/35132/list.htm']
    page_url = 'http://gs.zju.edu.cn/35132/list%d.htm'


class EarthSchoolPage31Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page31'
    source = '13'
    publisher = '地球科学学院'
    column = ['学院党建', '学院纪检']
    start_urls = ['http://gs.zju.edu.cn/35133/list.htm']
    page_url = 'http://gs.zju.edu.cn/35133/list%d.htm'


class EarthSchoolPage32Spider(EarthSchoolPage0Spider):
    name = 'earth_school_page32'
    source = '13'
    publisher = '地球科学学院'
    column = ['学院党建', '党建下载']
    start_urls = ['http://gs.zju.edu.cn/35134/list.htm']
    page_url = 'http://gs.zju.edu.cn/35134/list%d.htm'
