# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class EnvCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'env_college_page0'
    source = '17'
    publisher = '环境与资源学院'
    column = ['本科生教育', '信息公告']
    start_urls = ['https://webplus.zju.edu.cn/_s312/14553/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/14553/list%d.psp'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w14"]/ul[@class="clearfix"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="column-news-date news-date-hide"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class EnvCollegePage1Spider(EnvCollegePage0Spider):
    name = 'env_college_page1'
    source = '17'
    publisher = '环境与资源学院'
    column = ['本科生教育', '本科招生', '主修专业确认']
    start_urls = ['https://webplus.zju.edu.cn/_s312/16837/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/16837/list%d.psp'


class EnvCollegePage2Spider(EnvCollegePage0Spider):
    name = 'env_college_page2'
    source = '17'
    publisher = '环境与资源学院'
    column = ['本科生教育', '本科招生', '三位一体']
    start_urls = ['https://webplus.zju.edu.cn/_s312/swyt/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/swyt/list%d.psp'


class EnvCollegePage3Spider(EnvCollegePage0Spider):
    name = 'env_college_page3'
    source = '17'
    publisher = '环境与资源学院'
    column = ['本科生教育', '科研实践']
    start_urls = ['https://webplus.zju.edu.cn/_s312/kysj/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/kysj/list%d.psp'


class EnvCollegePage4Spider(EnvCollegePage0Spider):
    name = 'env_college_page4'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '信息公告']
    start_urls = ['https://webplus.zju.edu.cn/_s312/xxgg/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/xxgg/list%d.psp'


class EnvCollegePage5Spider(EnvCollegePage0Spider):
    name = 'env_college_page5'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '新闻动态']
    start_urls = ['https://webplus.zju.edu.cn/_s312/18303/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/18303/list%d.psp'


class EnvCollegePage6Spider(EnvCollegePage0Spider):
    name = 'env_college_page6'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '党建工作', '党务工作']
    start_urls = ['https://webplus.zju.edu.cn/_s312/dwgz/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/dwgz/list%d.psp'


class EnvCollegePage7Spider(EnvCollegePage0Spider):
    name = 'env_college_page7'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '团建工作', '组织工作']
    start_urls = ['https://webplus.zju.edu.cn/_s312/dwgz/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/dwgz/list%d.psp'


class EnvCollegePage8Spider(EnvCollegePage0Spider):
    name = 'env_college_page8'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '团建工作', '学术科技']
    start_urls = ['https://webplus.zju.edu.cn/_s312/xskj/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/xskj/list%d.psp'


class EnvCollegePage9Spider(EnvCollegePage0Spider):
    name = 'env_college_page9'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '团建工作', '社会实践']
    start_urls = ['https://webplus.zju.edu.cn/_s312/shsj/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/shsj/list%d.psp'


class EnvCollegePage10Spider(EnvCollegePage0Spider):
    name = 'env_college_page10'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '团建工作', '志愿服务']
    start_urls = ['https://webplus.zju.edu.cn/_s312/zyfw/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/zyfw/list%d.psp'


class EnvCollegePage11Spider(EnvCollegePage0Spider):
    name = 'env_college_page11'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '团建工作', '班团风采']
    start_urls = ['https://webplus.zju.edu.cn/_s312/btfc/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/btfc/list%d.psp'


class EnvCollegePage12Spider(EnvCollegePage0Spider):
    name = 'env_college_page12'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '本科生事务', '事务管理']
    start_urls = ['https://webplus.zju.edu.cn/_s312/swgl/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/swgl/list%d.psp'


class EnvCollegePage13Spider(EnvCollegePage0Spider):
    name = 'env_college_page13'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '本科生事务', '评奖评优']
    start_urls = ['https://webplus.zju.edu.cn/_s312/pjpy_26686/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/pjpy_26686/list%d.psp'


class EnvCollegePage14Spider(EnvCollegePage0Spider):
    name = 'env_college_page14'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '本科生事务', '勤工资助']
    start_urls = ['https://webplus.zju.edu.cn/_s312/qgzxyzz/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/qgzxyzz/list%d.psp'


class EnvCollegePage15Spider(EnvCollegePage0Spider):
    name = 'env_college_page15'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '本科生事务', '科研训练']
    start_urls = ['https://webplus.zju.edu.cn/_s312/kyxl/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/kyxl/list%d.psp'


class EnvCollegePage16Spider(EnvCollegePage0Spider):
    name = 'env_college_page16'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '本科生事务', '新生之友']
    start_urls = ['https://webplus.zju.edu.cn/_s312/xszy/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/xszy/list%d.psp'


class EnvCollegePage17Spider(EnvCollegePage0Spider):
    name = 'env_college_page17'
    source = '17'
    publisher = '环境与资源学院'
    column = ['学生在线', '表格下载']
    start_urls = ['https://webplus.zju.edu.cn/_s312/bgxz/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/bgxz/list%d.psp'


class EnvCollegePage18Spider(EnvCollegePage0Spider):
    name = 'env_college_page18'
    source = '17'
    publisher = '环境与资源学院'
    column = ['国际交流', '通知公告']
    start_urls = ['https://webplus.zju.edu.cn/_s312/14076/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/14076/list%d.psp'


class EnvCollegePage19Spider(EnvCollegePage0Spider):
    name = 'env_college_page19'
    source = '17'
    publisher = '环境与资源学院'
    column = ['国际交流', '出国出境', '学生出国出境']
    start_urls = ['https://webplus.zju.edu.cn/_s312/14596/list.psp']
    page_url = 'https://webplus.zju.edu.cn/_s312/14596/list%d.psp'
