# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class InterStudiesSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'inter_studies_school_page0'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['党政管理', '最新通知']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12554/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12554/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="news_list list2"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './span[@class="news_meta"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class InterStudiesSchoolPage1Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page1'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['党政管理', '党委文件']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12555/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12555/list%d.htm'


class InterStudiesSchoolPage2Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page2'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['党政管理', '资料中心']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12559/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12559/list%d.htm'


class InterStudiesSchoolPage3Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page3'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['党政管理', '实验中心']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12560/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12560/list%d.htm'


class InterStudiesSchoolPage4Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page4'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['党政管理', '工会之家']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12561/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12561/list%d.htm'


class InterStudiesSchoolPage5Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page5'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['党政管理', '常用信息']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12562/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12562/list%d.htm'


class InterStudiesSchoolPage6Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page6'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['科学研究', '最新通知']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12572/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12572/list%d.htm'


class InterStudiesSchoolPage7Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page7'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['科学研究', '各类申报']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12573/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12573/list%d.htm'


class InterStudiesSchoolPage8Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page8'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['科学研究', '学术动态']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12574/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12574/list%d.htm'


class InterStudiesSchoolPage9Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page9'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['科学研究', '科研成果']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12575/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12575/list%d.htm'


class InterStudiesSchoolPage10Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page10'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['科学研究', '常用信息']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12576/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12576/list%d.htm'


class InterStudiesSchoolPage11Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page11'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['本科教育', '最新通知']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12577/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12577/list%d.htm'


class InterStudiesSchoolPage12Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page12'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['本科教育', '学籍管理']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12578/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12578/list%d.htm'


class InterStudiesSchoolPage13Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page13'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['本科教育', '教学教务']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12579/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12579/list%d.htm'


class InterStudiesSchoolPage14Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page14'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['本科教育', '常用信息']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12583/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12583/list%d.htm'


class InterStudiesSchoolPage15Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page15'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['学生思政', '最新通知']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12593/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12593/list%d.htm'


class InterStudiesSchoolPage16Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page16'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['学生思政', '党团建设']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12594/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12594/list%d.htm'


class InterStudiesSchoolPage17Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page17'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['学生思政', '就业指导']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12595/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12595/list%d.htm'


class InterStudiesSchoolPage18Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page18'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['学生思政', '评奖评优']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12596/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12596/list%d.htm'


class InterStudiesSchoolPage19Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page19'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['学生思政', '学生资助']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12597/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12597/list%d.htm'


class InterStudiesSchoolPage20Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page20'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['学生思政', '公益实践']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12598/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12598/list%d.htm'


class InterStudiesSchoolPage21Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page21'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['学生思政', '学生组织']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12600/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12600/list%d.htm'


class InterStudiesSchoolPage22Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page22'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['学生思政', '常用信息']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12602/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12602/list%d.htm'


class InterStudiesSchoolPage23Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page23'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['对外交流', '最新通知']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12609/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12609/list%d.htm'


class InterStudiesSchoolPage24Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page24'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['对外交流', '地方合作']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12630/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12630/list%d.htm'


class InterStudiesSchoolPage25Spider(InterStudiesSchoolPage0Spider):
    name = 'inter_studies_school_page25'
    source = '19'
    publisher = '外国语言文化与国际交流学院'
    column = ['对外交流', '常用信息']
    start_urls = ['http://www.sis.zju.edu.cn/sischinese/12612/list.htm']
    page_url = 'http://www.sis.zju.edu.cn/sischinese/12612/list%d.htm'
