# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class MaterialsSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'materials_school_page0'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['最新通知', '重点提示']
    start_urls = ['https://mse.zju.edu.cn/51056/list.htm']
    page_url = 'https://mse.zju.edu.cn/51056/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w6"]/ul/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="news_meta"]/text()'
    publish_time_format = '%Y.%m.%d'
    publisher_group = '专业院系'


class MaterialsSchoolPage1Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page1'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['最新通知', '党政综合']
    start_urls = ['https://mse.zju.edu.cn/51057/list.htm']
    page_url = 'https://mse.zju.edu.cn/51057/list%d.htm'


class MaterialsSchoolPage2Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page2'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['最新通知', '本科生教育']
    start_urls = ['https://mse.zju.edu.cn/51058/list.htm']
    page_url = 'https://mse.zju.edu.cn/51058/list%d.htm'


class MaterialsSchoolPage3Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page3'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['最新通知', '国际交流']
    start_urls = ['https://mse.zju.edu.cn/51060/list.htm']
    page_url = 'https://mse.zju.edu.cn/51060/list%d.htm'


class MaterialsSchoolPage4Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page4'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['最新通知', '学生工作']
    start_urls = ['https://mse.zju.edu.cn/51062/list.htm']
    page_url = 'https://mse.zju.edu.cn/51062/list%d.htm'


class MaterialsSchoolPage5Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page5'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['最新通知', '实验室工作']
    start_urls = ['https://mse.zju.edu.cn/51063/list.htm']
    page_url = 'https://mse.zju.edu.cn/51063/list%d.htm'


class MaterialsSchoolPage6Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page6'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['最新通知', '科研开发']
    start_urls = ['https://mse.zju.edu.cn/51061/list.htm']
    page_url = 'https://mse.zju.edu.cn/51061/list%d.htm'


class MaterialsSchoolPage7Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page7'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['公告栏']
    start_urls = ['https://mse.zju.edu.cn/50928/list.htm']
    page_url = 'https://mse.zju.edu.cn/50928/list%d.htm'


class MaterialsSchoolPage8Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page8'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['学术活动']
    start_urls = ['https://mse.zju.edu.cn/50925/list.htm']
    page_url = 'https://mse.zju.edu.cn/50925/list%d.htm'


class MaterialsSchoolPage9Spider(MaterialsSchoolPage0Spider):
    name = 'materials_school_page9'
    source = '28'
    publisher = '材料科学与工程学院'
    column = ['微结构大赛']
    start_urls = ['http://mse.zju.edu.cn/50932/list.htm']
    page_url = 'http://mse.zju.edu.cn/50932/list%d.htm'
