# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class MathSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'math_school_page0'
    source = '29'
    publisher = '数学科学学院'
    column = ['本科生', '信息公告']
    start_urls = ['http://www.math.zju.edu.cn/38077/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38077/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w12"]//li'
    title_xpath = './/p[@class="title"]/text()'
    url_xpath = './a/@href'
    publish_time_xpath = 'custom'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class MathSchoolPage1Spider(MathSchoolPage0Spider):
    name = 'math_school_page1'
    source = '29'
    publisher = '数学科学学院'
    column = ['本科生', '学籍管理']
    start_urls = ['http://www.math.zju.edu.cn/38080/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38080/list%d.htm'


class MathSchoolPage2Spider(MathSchoolPage0Spider):
    name = 'math_school_page2'
    source = '29'
    publisher = '数学科学学院'
    column = ['本科生', '科研训练']
    start_urls = ['http://www.math.zju.edu.cn/38081/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38081/list%d.htm'


class MathSchoolPage3Spider(MathSchoolPage0Spider):
    name = 'math_school_page3'
    source = '29'
    publisher = '数学科学学院'
    column = ['本科生', '政策文件']
    start_urls = ['http://www.math.zju.edu.cn/38082/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38082/list%d.htm'


class MathSchoolPage4Spider(MathSchoolPage0Spider):
    name = 'math_school_page4'
    source = '29'
    publisher = '数学科学学院'
    column = ['本科生', '招生工作']
    start_urls = ['http://www.math.zju.edu.cn/38083/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38083/list%d.htm'


class MathSchoolPage5Spider(MathSchoolPage0Spider):
    name = 'math_school_page5'
    source = '29'
    publisher = '数学科学学院'
    column = ['党群学工', '学生新闻通知']
    start_urls = ['http://www.math.zju.edu.cn/38098/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38098/list%d.htm'


class MathSchoolPage6Spider(MathSchoolPage0Spider):
    name = 'math_school_page6'
    source = '29'
    publisher = '数学科学学院'
    column = ['党群学工', '就业信息']
    start_urls = ['http://www.career.zju.edu.cn/jyxt/jyweb/xywzIndex.zf?wzid=A47AB86DA64380C5E055134CA39C9BD7']
    page_url = 'http://www.career.zju.edu.cn/jyxt/jyweb/xywzIndex.zf?wzid=A47AB86DA64380C5E055134CA39C9BD7list%d.htm'


class MathSchoolPage7Spider(MathSchoolPage0Spider):
    name = 'math_school_page7'
    source = '29'
    publisher = '数学科学学院'
    column = ['党群学工', '评奖评优']
    start_urls = ['http://www.math.zju.edu.cn/38100/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38100/list%d.htm'


class MathSchoolPage8Spider(MathSchoolPage0Spider):
    name = 'math_school_page8'
    source = '29'
    publisher = '数学科学学院'
    column = ['党群学工', '学生资助']
    start_urls = ['http://www.math.zju.edu.cn/38101/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38101/list%d.htm'


class MathSchoolPage9Spider(MathSchoolPage0Spider):
    name = 'math_school_page9'
    source = '29'
    publisher = '数学科学学院'
    column = ['党群学工', '学生文件资料']
    start_urls = ['http://www.math.zju.edu.cn/38102/list.htm']
    page_url = 'http://www.math.zju.edu.cn/38102/list%d.htm'


class MathSchoolPage10Spider(MathSchoolPage0Spider):
    name = 'math_school_page10'
    source = '29'
    publisher = '数学科学学院'
    column = ['通知公告', '重要通知']
    start_urls = ['http://www.math.zju.edu.cn/zytz/list.htm']
    page_url = 'http://www.math.zju.edu.cn/zytz/list%d.htm'


class MathSchoolPage11Spider(MathSchoolPage0Spider):
    name = 'math_school_page11'
    source = '29'
    publisher = '数学科学学院'
    column = ['通知公告', '本科生']
    start_urls = ['http://www.math.zju.edu.cn/bkstz/list.htm']
    page_url = 'http://www.math.zju.edu.cn/bkstz/list%d.htm'
