# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class SoftwareCollegePage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'software_college_page0'
    source = '40'
    publisher = '软件学院'
    column = ['教学管理', '教务信息']
    start_urls = ['http://www.cst.zju.edu.cn/36216/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36216/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@class="lm_new"]/ul/li'
    title_xpath = './/a/text()'
    url_xpath = './/a/@href'
    publish_time_xpath = './span[@class="fr"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '专业院系'


class SoftwareCollegePage1Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page1'
    source = '40'
    publisher = '软件学院'
    column = ['教学管理', '论文管理']
    start_urls = ['http://www.cst.zju.edu.cn/36217/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36217/list%d.htm'


class SoftwareCollegePage2Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page2'
    source = '40'
    publisher = '软件学院'
    column = ['思政工作', '重要信息']
    start_urls = ['http://www.cst.zju.edu.cn/36224/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36224/list%d.htm'


class SoftwareCollegePage3Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page3'
    source = '40'
    publisher = '软件学院'
    column = ['思政工作', '党团信息']
    start_urls = ['http://www.cst.zju.edu.cn/36227/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36227/list%d.htm'


class SoftwareCollegePage4Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page4'
    source = '40'
    publisher = '软件学院'
    column = ['思政工作', '评奖评优']
    start_urls = ['http://www.cst.zju.edu.cn/36228/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36228/list%d.htm'


class SoftwareCollegePage5Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page5'
    source = '40'
    publisher = '软件学院'
    column = ['思政工作', '困难资助', '困难资助']
    start_urls = ['http://www.cst.zju.edu.cn/36229/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36229/list%d.htm'


class SoftwareCollegePage6Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page6'
    source = '40'
    publisher = '软件学院'
    column = ['思政工作', '困难资助', '勤工助学']
    start_urls = ['http://www.cst.zju.edu.cn/36270/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36270/list%d.htm'


class SoftwareCollegePage7Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page7'
    source = '40'
    publisher = '软件学院'
    column = ['思政工作', '困难资助', '困难补助']
    start_urls = ['http://www.cst.zju.edu.cn/36271/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36271/list%d.htm'


class SoftwareCollegePage8Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page8'
    source = '40'
    publisher = '软件学院'
    column = ['思政工作', '困难资助', '助学贷款']
    start_urls = ['http://www.cst.zju.edu.cn/36272/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36272/list%d.htm'


class SoftwareCollegePage9Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page9'
    source = '40'
    publisher = '软件学院'
    column = ['实习就业', '学生实习', '招聘信息']
    start_urls = ['http://www.cst.zju.edu.cn/36273/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36273/list%d.htm'


class SoftwareCollegePage10Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page10'
    source = '40'
    publisher = '软件学院'
    column = ['实习就业', '国际实习']
    start_urls = ['http://www.cst.zju.edu.cn/36235/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36235/list%d.htm'


class SoftwareCollegePage11Spider(SoftwareCollegePage0Spider):
    name = 'software_college_page11'
    source = '40'
    publisher = '软件学院'
    column = ['实习就业', '学生就业', '招聘信息']
    start_urls = ['http://www.cst.zju.edu.cn/36236/list.htm']
    page_url = 'http://www.cst.zju.edu.cn/36236/list%d.htm'
