# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class UndergraduateSchoolPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'undergraduate_school_page0'
    source = '41'
    publisher = '本科生院'
    column = ['新闻动态', '新闻动态']
    start_urls = ['http://ugrs.zju.edu.cn/_t1258/28259/list.htm']
    page_url = 'http://ugrs.zju.edu.cn/_t1258/28259/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w17"]/li'
    title_xpath = './a/text()'
    url_xpath = './a/@href'
    publish_time_xpath = './span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '行政部门'


class UndergraduateSchoolPage1Spider(UndergraduateSchoolPage0Spider):
    name = 'undergraduate_school_page1'
    source = '41'
    publisher = '本科生院'
    column = ['新闻动态', '媒体报道']
    start_urls = ['http://ugrs.zju.edu.cn/28260/list.htm']
    page_url = 'http://ugrs.zju.edu.cn/28260/list%d.htm'


class UndergraduateSchoolPage2Spider(UndergraduateSchoolPage0Spider):
    name = 'undergraduate_school_page2'
    source = '41'
    publisher = '本科生院'
    column = ['科研训练', '校院级']
    start_urls = ['http://ugrs.zju.edu.cn/28192/list.htm']
    page_url = 'http://ugrs.zju.edu.cn/28192/list%d.htm'


class UndergraduateSchoolPage3Spider(UndergraduateSchoolPage0Spider):
    name = 'undergraduate_school_page3'
    source = '41'
    publisher = '本科生院'
    column = ['科研训练', '省级']
    start_urls = ['http://ugrs.zju.edu.cn/28193/list.htm']
    page_url = 'http://ugrs.zju.edu.cn/28193/list%d.htm'


class UndergraduateSchoolPage4Spider(UndergraduateSchoolPage0Spider):
    name = 'undergraduate_school_page4'
    source = '41'
    publisher = '本科生院'
    column = ['科研训练', '国家级']
    start_urls = ['http://ugrs.zju.edu.cn/28194/list.htm']
    page_url = 'http://ugrs.zju.edu.cn/28194/list%d.htm'


class UndergraduateSchoolPage5Spider(UndergraduateSchoolPage0Spider):
    name = 'undergraduate_school_page5'
    source = '41'
    publisher = '本科生院'
    column = ['学科竞赛']
    start_urls = ['http://ugrs.zju.edu.cn/28190/list.htm']
    page_url = 'http://ugrs.zju.edu.cn/28190/list%d.htm'
