# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class UndergraduateSchoolExtraPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'undergraduate_school_extra_page0'
    source = '41'
    publisher = '本科生院'
    column = ['教学培养', '专业教育']
    start_urls = ['http://bksy.zju.edu.cn/28324/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28324/list%d.htm'
    initial_page = 1
    list_xpath = '//div[@id="wp_news_w24"]/li'
    title_xpath = './a/text()'
    url_xpath = './a/@href'
    publish_time_xpath = './span/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '行政部门'


class UndergraduateSchoolExtraPage1Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page1'
    source = '41'
    publisher = '本科生院'
    column = ['教学培养', '课程建设']
    start_urls = ['http://bksy.zju.edu.cn/28326/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28326/list%d.htm'


class UndergraduateSchoolExtraPage2Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page2'
    source = '41'
    publisher = '本科生院'
    column = ['学籍管理', '办事指南']
    start_urls = ['http://bksy.zju.edu.cn/28337/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28337/list%d.htm'


class UndergraduateSchoolExtraPage3Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page3'
    source = '41'
    publisher = '本科生院'
    column = ['学籍管理', '注册报到']
    start_urls = ['http://bksy.zju.edu.cn/28338/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28338/list%d.htm'


class UndergraduateSchoolExtraPage4Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page4'
    source = '41'
    publisher = '本科生院'
    column = ['学籍管理', '学籍异动']
    start_urls = ['http://bksy.zju.edu.cn/28339/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28339/list%d.htm'


class UndergraduateSchoolExtraPage5Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page5'
    source = '41'
    publisher = '本科生院'
    column = ['学籍管理', '主修专业确认']
    start_urls = ['http://bksy.zju.edu.cn/28340/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28340/list%d.htm'


class UndergraduateSchoolExtraPage6Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page6'
    source = '41'
    publisher = '本科生院'
    column = ['学籍管理', '毕业于学位']
    start_urls = ['http://bksy.zju.edu.cn/28341/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28341/list%d.htm'


class UndergraduateSchoolExtraPage7Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page7'
    source = '41'
    publisher = '本科生院'
    column = ['学籍管理', '保送研究生']
    start_urls = ['http://bksy.zju.edu.cn/28342/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28342/list%d.htm'


class UndergraduateSchoolExtraPage8Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page8'
    source = '41'
    publisher = '本科生院'
    column = ['学籍管理', '政策解答']
    start_urls = ['http://bksy.zju.edu.cn/28343/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28343/list%d.htm'


class UndergraduateSchoolExtraPage9Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page9'
    source = '41'
    publisher = '本科生院'
    column = ['学籍管理', '出国成绩办理预约']
    start_urls = ['http://bksy.zju.edu.cn/28344/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28344/list%d.htm'


class UndergraduateSchoolExtraPage10Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page10'
    source = '41'
    publisher = '本科生院'
    column = ['实践教学', '实验']
    start_urls = ['http://bksy.zju.edu.cn/28346/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28346/list%d.htm'


class UndergraduateSchoolExtraPage11Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page11'
    source = '41'
    publisher = '本科生院'
    column = ['实践教学', '实习']
    start_urls = ['http://bksy.zju.edu.cn/28347/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28347/list%d.htm'


class UndergraduateSchoolExtraPage12Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page12'
    source = '41'
    publisher = '本科生院'
    column = ['实践教学', '毕业论文(设计)']
    start_urls = ['http://bksy.zju.edu.cn/28348/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28348/list%d.htm'


class UndergraduateSchoolExtraPage13Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page13'
    source = '41'
    publisher = '本科生院'
    column = ['文件汇编', '内部管理']
    start_urls = ['http://bksy.zju.edu.cn/nbgl/list.htm']
    page_url = 'http://bksy.zju.edu.cn/nbgl/list%d.htm'


class UndergraduateSchoolExtraPage14Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page14'
    source = '41'
    publisher = '本科生院'
    column = ['文件汇编', '学生日常学习事务']
    start_urls = ['http://bksy.zju.edu.cn/28375/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28375/list%d.htm'


class UndergraduateSchoolExtraPage15Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page15'
    source = '41'
    publisher = '本科生院'
    column = ['文件汇编', '竺可桢学院教学事务']
    start_urls = ['http://bksy.zju.edu.cn/28379/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28379/list%d.htm'


class UndergraduateSchoolExtraPage16Spider(UndergraduateSchoolExtraPage0Spider):
    name = 'undergraduate_school_extra_page16'
    source = '41'
    publisher = '本科生院'
    column = ['文件汇编', '其他']
    start_urls = ['http://bksy.zju.edu.cn/28381/list.htm']
    page_url = 'http://bksy.zju.edu.cn/28381/list%d.htm'
