# HTML Spider Generator version 3.3
# --------------------------------
# This file is automatically generated by HTML spider generator, a tool used to generate spider.
# Please copy or move this file to notify_scrapy/spiders and test to make sure it can fetch notices
# properly before deploying it.
# It is not recommended to modify this file directly. If the spider does not work properly, please
# check if it is outdated. Current version of spider can be find in Spider's properties.

from notify_scrapy.base_html_spider import BaseHTMLSpider


class YunfengCommunityPage0Spider(BaseHTMLSpider):
    generator_version = '3.3'
    name = 'yunfeng_community_page0'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生党建', '通知公告']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53524/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53524/list%d.htm'
    initial_page = 1
    list_xpath = '//ul[@class="news_list list2"]/li'
    title_xpath = './/a/@title'
    url_xpath = './/a/@href'
    publish_time_xpath = './/span[@class="news_meta"]/text()'
    publish_time_format = '%Y-%m-%d'
    publisher_group = '学园行政'


class YunfengCommunityPage1Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page1'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生党建', '新闻动态']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53525/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53525/list%d.htm'


class YunfengCommunityPage2Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page2'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生党建', '理论学习']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53526/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53526/list%d.htm'


class YunfengCommunityPage3Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page3'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生党建', '党建教育基地']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53527/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53527/list%d.htm'


class YunfengCommunityPage4Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page4'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生团建', '通知动态']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53529/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53529/list%d.htm'


class YunfengCommunityPage5Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page5'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生事务', '评奖评优']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53709/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53709/list%d.htm'


class YunfengCommunityPage6Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page6'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生事务', '学生资助', '通知公告']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53714/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53714/list%d.htm'


class YunfengCommunityPage7Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page7'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生事务', '学生资助', 'NSEP']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53715/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53715/list%d.htm'


class YunfengCommunityPage8Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page8'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生事务', '活动记实']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53712/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53712/list%d.htm'


class YunfengCommunityPage9Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page9'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['学生事务', '心理健康', '通知公告']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53713/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53713/list%d.htm'


class YunfengCommunityPage10Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page10'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['教学教务', '最新通知']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53519/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53519/list%d.htm'


class YunfengCommunityPage11Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page11'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['教学教务', '培养方案']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53520/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53520/list%d.htm'


class YunfengCommunityPage12Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page12'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['教学教务', '学业指导']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53521/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53521/list%d.htm'


class YunfengCommunityPage13Spider(YunfengCommunityPage0Spider):
    name = 'yunfeng_community_page13'
    source = '42'
    publisher = '紫云碧峰学园'
    column = ['教学教务', '相关文件']
    start_urls = ['http://yunfeng.zju.edu.cn/on/53522/list.htm']
    page_url = 'http://yunfeng.zju.edu.cn/on/53522/list%d.htm'
